/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SAAceSerializable.h"

@class NSURL;

@protocol SAAceIdentifiable <SAAceSerializable>
@property(copy, nonatomic) NSURL* identifier;
@end

