/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

@interface SBAceClassMap : XXUnknownSuperclass {
	NSMutableDictionary* _classMap;
}
-(id)init;
-(void)dealloc;
-(void)addBundle:(id)bundle objCClassName:(id)name forAceClass:(id)aceClass inGroup:(id)group;
-(id)entryForAceClass:(id)aceClass inGroup:(id)group;
-(id)bundleForAceClass:(id)aceClass inGroup:(id)group;
-(id)classNameForAceClass:(id)aceClass inGroup:(id)group;
-(id)description;
@end

