/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIView;

@interface SBActivationView : XXUnknownSuperclass {
	UIView* _backgroundView;
	int _mode;
}
-(id)initWithFrame:(CGRect)frame mode:(int)mode;
-(int)mode;
-(void)dealloc;
@end

