/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDisplay.h"
#import "SpringBoard-Structs.h"

@class NSMutableDictionary, SBAlertWindow, SBAlertDisplay;

@interface SBAlert : SBDisplay {
	SBAlertDisplay* _display;
	NSMutableDictionary* _dictionary;
	SBAlertWindow* _deferredAlertWindow;
}
+(void)registerForAlerts;
+(id)alertWindow;
+(void)test;
+(void)activateAlertForController:(id)controller animated:(BOOL)animated animateCurrentDisplayOut:(BOOL)anOut withDelay:(BOOL)delay isSlidingDisplay:(BOOL)display;
+(void)deactivateAlertForController:(id)controller animated:(BOOL)animated animateOldDisplayInWithStyle:(int)style isSlidingDisplay:(BOOL)display;
+(void)alertAdapterDisplayDidDisappear:(id)alertAdapterDisplay;
+(id)_adapterForController:(id)controller;
-(void)dealloc;
-(id)display;
-(void)setDisplay:(id)display;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(void)setObject:(id)object forKey:(id)key;
-(id)objectForKey:(id)key;
-(void)removeObjectForKey:(id)key;
-(BOOL)allowsStackingOfAlert:(id)alert;
-(BOOL)undimsDisplay;
-(BOOL)showsSpringBoardStatusBar;
-(float)finalAlpha;
-(CGRect)alertWindowRect;
-(Class)alertWindowClass;
-(void)_updateStatusBarLockAndTime;
-(int)statusBarStyleOverridesToCancel;
-(void)activate;
-(void)tearDownAlertWindow:(id)window;
-(int)interfaceOrientationForActivation;
-(void)removeFromView;
-(void)deactivate;
-(int)effectiveStatusBarStyle;
-(double)autoDimTime;
-(int)statusBarStyle;
-(void)didAnimateLockKeypadIn;
-(void)didAnimateLockKeypadOut;
-(void)didFinishAnimatingIn;
-(void)didFinishAnimatingOut;
-(BOOL)handleMenuButtonTap;
-(BOOL)shouldDeactivateAlertItemsOnActivation;
-(BOOL)hasTranslucentBackground;
-(BOOL)handleLockButtonPressed;
-(BOOL)handleVolumeUpButtonPressed;
-(BOOL)handleVolumeDownButtonPressed;
-(BOOL)handleHeadsetButtonPressed:(BOOL)pressed;
-(BOOL)suppressesNotifications;
@end

