/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "BBObserverDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class NSMutableArray, NSTimer, CPDistributedNotificationCenter, BBObserver;

@interface SBAlertItemsController : XXUnknownSuperclass <BBObserverDelegate> {
	NSMutableArray* _lockedAlertItems;
	NSMutableArray* _unlockedAlertItems;
	NSMutableArray* _pendingAlertItems;
	NSTimer* _autoDismissTimer;
	CPDistributedNotificationCenter* _notificationCenter;
	unsigned _notificationClientCount;
	BOOL _systemShuttingDown;
	BOOL _forceAlertsToPend;
	BBObserver* _bbObserver;
}
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(id)description;
-(void)convertUnlockedAlertsToLockedAlerts;
-(void)resetAutoDismissTimer;
-(void)activateAlertItem:(id)item;
-(void)deactivateAlertItem:(id)item reason:(int)reason;
-(void)deactivateAlertItem:(id)item reason:(int)reason animated:(BOOL)animated;
-(void)deactivateAlertItem:(id)item;
-(void)deactivateAlertItemsOfClass:(Class)aClass;
-(void)deactivateAlertItemsOfClass:(Class)aClass reason:(int)reason;
-(void)deactivateAlertItemsOfClass:(Class)aClass reason:(int)reason animated:(BOOL)animated;
-(void)deactivateVisibleAlertItemOfClass:(Class)aClass reason:(int)reason;
-(void)autoDismissAlertItem:(id)item;
-(id)alertItemOfClass:(Class)aClass;
-(id)alertItemsOfClass:(Class)aClass;
-(BOOL)hasAlertOfClass:(Class)aClass;
-(BOOL)hasAlerts;
-(BOOL)hasVisibleAlert;
-(id)visibleAlertItem;
-(BOOL)canDeactivateAlertForMenuClickOrSystemGesture;
-(BOOL)deactivateAlertForMenuClickOrSystemGestureWithAnimation:(BOOL)animation;
-(id)deactivateAlertItemsForLock;
-(BOOL)dontLockOverAlertItems;
-(void)deactivateAlertItemsForAlertActivation;
-(void)noteVolumeOrLockPressedOverLockedAlerts;
-(void)_postAlertPresentedNotificationForType:(int)type sender:(id)sender date:(id)date;
-(void)notifySystemOfAlertItemActivation:(id)alertItemActivation;
-(void)noteSystemShuttingDown;
-(void)setForceAlertsToPend:(BOOL)pend;
-(void)forceAlertsToPendAndMoveActiveAlertsToPendingWithAnimation:(BOOL)animation;
-(void)_notificationClientStarted:(id)started;
-(void)_notificationClientEnded:(id)ended;
-(void)_buddyDidExit;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
@end

