/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class CADisplayLink, NSArray, UIView;

@interface SBAnimationStepper : XXUnknownSuperclass {
	id m_delegate;
	UIView* m_view;
	NSArray* m_animatingSubviews;
	double m_duration;
	float m_percentage;
	CADisplayLink* m_displayLink;
	double m_finishBackwardTimestamp;
	double m_finishBackwardDuration;
	float m_finishBackwardPercentage;
}
@property(assign, nonatomic) id delegate;
@property(retain, nonatomic) UIView* view;
@property(copy, nonatomic) NSArray* animatingSubviews;
@property(assign, nonatomic) double duration;
@property(assign, nonatomic) float percentage;
-(id)init;
-(void)dealloc;
-(void)stepAnimationsInView:(id)view animatingSubviews:(id)subviews duration:(double)duration;
-(void)finishForwardToEnd;
-(void)finishBackwardToStart;
-(void)updateFinishBackwardToStart:(id)start;
@end

