/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class NSMutableDictionary, NSString, NSMutableArray, SBAppContextHostView;

@interface SBAppContextHostManager : XXUnknownSuperclass {
	SBAppContextHostView* _contextHostView;
	NSString* _appBundleID;
	NSMutableArray* _contexts;
	BOOL _hostingEnabled;
	NSMutableArray* _hostRequesters;
	NSMutableDictionary* _hostRequesterInfo;
}
@property(copy, nonatomic) NSString* appBundleID;
@property(readonly, assign, nonatomic, getter=isHostingEnabled) BOOL hostingEnabled;
@property(readonly, assign, nonatomic) unsigned contextCount;
-(id)init;
-(void)dealloc;
-(id)description;
-(id)hostViewForRequester:(id)requester;
-(void)enableHostingForRequester:(id)requester orderFront:(BOOL)front;
-(void)disableHostingForRequester:(id)requester;
-(void)disableHostingForAllRequesters;
-(void)orderRequesterFront:(id)front;
-(void)setContextId:(unsigned)anId hidden:(BOOL)hidden forRequester:(id)requester;
-(id)_realContextHostViewWhichIReallyNeedToAccessAndIKnowWhatImDoingISwear;
-(void)_notePropertiesSetOnRealContextHostViewWhichIReallyNeedToChangeAndIKnowWhatImDoingISwear:(id)changeAndIKnowWhatImDoingISwear originalProperties:(id)properties forRequester:(id)requester;
-(BOOL)_requesterIsFrontmost:(id)frontmost;
-(id)_infoForRequester:(id)requester;
-(void)_applyRequesterInfo:(id)info;
-(void)_removeRequesterInfo:(id)info;
-(void)_setContext:(id)context hidden:(BOOL)hidden;
-(void)willOrderInContextWithId:(unsigned)anId windowLevel:(float)level windowOutput:(int)output flush:(BOOL)flush;
-(void)didOrderOutContextWithId:(unsigned)anId;
-(void)setOrderOutPending:(BOOL)pending forContextId:(unsigned)contextId;
-(void*)createIOSurfaceForFrame:(CGRect)frame;
-(void*)createIOSurfaceForFrame:(CGRect)frame outTransform:(CGAffineTransform*)transform;
-(void*)createIOSurfaceForFrame:(CGRect)frame excludeContext:(unsigned)context outTransform:(CGAffineTransform*)transform;
-(void*)createIOSurfaceForFrame:(CGRect)frame excludeContext:(unsigned)context usePurpleGfx:(BOOL)gfx outTransform:(CGAffineTransform*)transform;
-(void)_adjustLayerFrameAndTransform:(id)transform;
@end

