/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBAppToAppTransitionView.h"


@interface SBAppShuffleView : SBAppToAppTransitionView {
}
-(void)beginTransition;
-(void)endTransition;
@end

