/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface SBApplicationUninstallationOperation : XXUnknownSuperclass {
	NSString* _bundleIdentifier;
}
-(id)initWithBundleIdentifier:(id)bundleIdentifier;
-(void)dealloc;
-(void)main;
@end

