/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBAppToAppTransitionView, UIWindow;

@interface SBAppToAppTransitionController : XXUnknownSuperclass {
	UIWindow* _transitionWindow;
	SBAppToAppTransitionView* _transitionView;
}
@property(readonly, assign, nonatomic) SBAppToAppTransitionView* transitionView;
-(id)init;
-(void)dealloc;
-(void)beginTransition;
-(void)endTransition;
@end

