/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

@interface SBApplicationPersistence : XXUnknownSuperclass {
	NSMutableDictionary* _state;
	BOOL _dirty;
	dispatch_queue_s* _stateQueue;
	dispatch_queue_s* _writeQueue;
}
+(id)sharedInstance;
+(id)_statePath;
+(void)migrateSystemLocalNotifications;
-(id)init;
-(id)valueForKey:(id)key bundleOrDisplayIdentifier:(id)identifier ofType:(Class)type;
-(void)setValue:(id)value forKey:(id)key bundleOrDisplayIdentifier:(id)identifier;
-(id)archivedObjectForKey:(id)key bundleOrDisplayIdentifier:(id)identifier ofType:(Class)type;
-(void)setArchivedObject:(id)object forKey:(id)key bundleOrDisplayIdentifier:(id)identifier;
-(id)allBundleOrDisplayIdentifiersWithState;
-(void)purgeKeysForBundleAndDisplayIdentifiersOtherThan:(id)bundleAndDisplayIdentifiersOtherThan;
-(void)flushSynchronously;
-(void)_flushSynchronously;
-(void)_markDirty;
@end

