/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIAlertViewDelegate.h"

@class SBUserInstalledApplicationIcon, UIButton;

@interface SBAppRatingsAlertItem : XXUnknownSuperclass <UIAlertViewDelegate> {
	SBUserInstalledApplicationIcon* _icon;
	UIButton* _rateButton;
	BOOL _uninstallOnDismiss;
}
-(id)initWithIcon:(id)icon uninstallOnDismiss:(BOOL)dismiss;
-(void)dealloc;
-(Class)alertSheetClass;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)_starsControlValueChanged:(id)changed;
-(BOOL)shouldShowInLockScreen;
-(BOOL)dismissOnLock;
@end

