/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAppSwitcherScrollViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBAppSwitcherScrollView, SBLinenView, UIView, NSMutableArray;
@protocol SBAppSwitcherBarViewDelegate;

@interface SBAppSwitcherBarView : XXUnknownSuperclass <SBAppSwitcherScrollViewDelegate> {
	id<SBAppSwitcherBarViewDelegate> _delegate;
	NSMutableArray* _appIcons;
	UIView* _contentView;
	SBLinenView* _backgroundView;
	NSMutableArray* _auxViews;
	SBAppSwitcherScrollView* _scrollView;
	BOOL _animateContentReflow;
	BOOL _animatedScrolling;
	int _lastPageIndex;
	BOOL _isVisible;
	CGPoint _savedPositionForSuspendGesture;
}
@property(assign, nonatomic) id<SBAppSwitcherBarViewDelegate> delegate;
+(unsigned)iconsPerPage:(int)page;
+(CGSize)viewSize:(int)size;
+(float)edgePaddingForWidth:(float)width;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)prepareIconViewsForDisplay:(id)display showFirstPage:(BOOL)page;
-(id)iconViews;
-(void)setEditing:(BOOL)editing;
-(BOOL)isScrolling;
-(void)addIcon:(id)icon;
-(void)removeIcon:(id)icon;
-(void)replaceIcons:(id)icons with:(id)with;
-(void)addAuxiliaryViews:(id)views;
-(BOOL)nowPlayingControlsVisible;
-(BOOL)airPlayControlsVisible;
-(void)viewWillAppear;
-(void)viewWillDisappear;
-(void)_iconRemoveDidStop:(id)_iconRemove finished:(id)finished context:(id)context;
-(void)_reflowContent:(BOOL)content;
-(void)_adjustContentOffsetForReflow:(BOOL)reflow;
-(void)_adjustContentOffsetForResizeFromOldOffset:(CGPoint)oldOffset andOldSize:(CGSize)size toNewSize:(CGSize)newSize;
-(void)_adjustScrollContentSize;
-(void)_positionAtFirstPage:(BOOL)firstPage;
-(void)layoutSubviews;
-(CGRect)_iconFrameForIndex:(unsigned)index withSize:(CGSize)size;
-(unsigned)_pageCount;
-(unsigned)_iconCountForWidth:(float)width;
-(CGPoint)_firstPageOffset:(CGSize)offset;
-(int)_pageForOffset:(CGPoint)offset withSize:(CGSize)size;
-(int)_pageForIndex:(unsigned)index;
-(void)didMoveToSuperview;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)scrollViewDidEndScrollingAnimation:(id)scrollView;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(void)scrollViewDidEndDecelerating:(id)scrollView;
-(BOOL)scrollView:(id)view shouldCancelInContentForView:(id)view2;
-(void)saveScrollPositionBeforeSuspendGesture;
-(void)restoreScrollPositionAfterSuspendGesture;
@end

