/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class AFUIUtteranceView, SBAssistantInitialQueryInstructionsController, NSString;

@interface SBAssistantInitialQueryController : XXUnknownSuperclass {
	NSString* _text;
	SBAssistantInitialQueryInstructionsController* _helpController;
	AFUIUtteranceView* _view;
}
@property(retain, nonatomic) NSString* text;
-(void)dealloc;
-(id)view;
@end

