/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SAUIConfirmationOptions, SBAssistantConfirmView;

@interface SBAssistantConfirmController : XXUnknownSuperclass {
	SBAssistantConfirmView* _view;
	SAUIConfirmationOptions* _model;
	int _confirmTrigger;
}
-(id)initWithAceObject:(id)aceObject delegate:(id)delegate;
-(void)dealloc;
-(BOOL)_wantsStaticPresentation;
-(id)view;
-(void)_sendCommandsAndDismiss:(id)dismiss stampingMostRecentSnippetWithCancel:(BOOL)cancel;
-(void)_cancelButtonHit:(id)hit;
-(void)_confirmButtonHit:(id)hit;
@end

