/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBAssistantGuideDomainListDelegate <NSObject>
-(void)assistantShowSectionsForDomainAtIndex:(unsigned)index;
@end

