/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIImageView;
@protocol SBAssistantGuideDomainListCellDelegate;

@interface SBAssistantGuideDomainListCell : XXUnknownSuperclass {
	id<SBAssistantGuideDomainListCellDelegate> _delegate;
	UIImageView* _iconView;
	UILabel* _tagPhraseLabel;
	UILabel* _domainNameLabel;
	UIImageView* _chevronView;
	UIImageView* _separator;
}
@property(assign, nonatomic) id<SBAssistantGuideDomainListCellDelegate> delegate;
+(float)rowHeight;
-(id)initWithReuseIdentifier:(id)reuseIdentifier;
-(void)dealloc;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)setDomainName:(id)name;
-(void)setTagPhrase:(id)phrase;
-(void)setIconImage:(id)image;
-(void)prepareForReuse;
-(void)layoutSubviews;
@end

