/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class AFUIUtteranceView;

@interface SBAssistantGuideSectionListCell : XXUnknownSuperclass {
	AFUIUtteranceView* _bubbleView;
	CGSize _currentSize;
}
-(id)initWithReuseIdentifier:(id)reuseIdentifier;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)dealloc;
-(void)setPhrase:(id)phrase;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)layoutSubviews;
-(float)currentHeight;
@end

