/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIView;

@interface SBAssistantAwayBottomView : XXUnknownSuperclass {
	UIView* _lockBarView;
	UIView* _backgroundView;
	BOOL _open;
}
-(id)initWithFrame:(CGRect)frame;
-(id)initWithAwayView:(id)awayView;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setOpen:(BOOL)open;
@end

