/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBAssistantController;

@interface SBAssistantFullyRevealedState : XXUnknownSuperclass {
	SBAssistantController* _controller;
	id _block;
}
@property(retain, nonatomic) SBAssistantController* controller;
@property(retain, nonatomic) id block;
+(id)stateWithController:(id)controller block:(id)block;
-(void)dealloc;
@end

