/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController;

@interface SBAssistantInitialQueryInstructionsController : XXUnknownSuperclass {
	UIViewController* _parent;
}
@property(retain, nonatomic) UIViewController* parent;
-(void)dealloc;
-(void)loadView;
-(void)_doneButtonHit:(id)hit;
@end

