/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class AFUISnippetController, NSString;
@protocol SBAssistantTableViewCellDelegate;

@interface SBAssistantTableViewCell : XXUnknownSuperclass {
	id<SBAssistantTableViewCellDelegate> _delegate;
	AFUISnippetController* _controller;
	NSString* _animationName;
}
@property(assign, nonatomic) id<SBAssistantTableViewCellDelegate> delegate;
@property(retain, nonatomic) AFUISnippetController* controller;
@property(readonly, assign, nonatomic) NSString* animationName;
+(float)defaultSnippetViewInset;
-(void)dealloc;
-(void)setController:(id)controller parentingViewInCell:(BOOL)cell;
-(void)parentViewInCell;
-(BOOL)isViewInCell;
-(void)layoutSubviews;
-(void)removeFromSuperview;
-(id)description;
-(void)addSnippetAnimation:(id)animation named:(id)named;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
@end

