/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, SBAceClassMap;

@interface SBAssistantUIPluginManager : XXUnknownSuperclass {
	NSMutableDictionary* _pluginBundles;
	SBAceClassMap* _snippetClassMap;
	SBAceClassMap* _disambiguationListItemClassMap;
	SBAceClassMap* _providerClassMap;
}
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(id)_loadBundleAndGetClassNameForAceClass:(id)aceClass group:(id)group fromMap:(id)map;
-(id)bundleForBundleIdentifier:(id)bundleIdentifier;
-(Class)snippetClassForObject:(id)object;
-(id)snippetControllerForObject:(id)object withDelegate:(id)delegate;
-(id)speakableProviderForObject:(id)object;
-(id)disambiguationCellForObject:(id)object context:(id)context;
-(id)_bundleSearchPaths;
-(void)_loadBundleMapsIfNecessary;
-(id)_snippetMapForDomainDictionary:(id)domainDictionary inBundle:(id)bundle;
-(id)_listItemMapForDomainDictionary:(id)domainDictionary;
-(id)_providerMapForDomainDictionary:(id)domainDictionary;
@end

