/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol SBAssistantSpaceViewDelegate;

@interface SBAssistantSpaceView : XXUnknownSuperclass {
	id<SBAssistantSpaceViewDelegate> _delegate;
}
@property(assign, nonatomic) id<SBAssistantSpaceViewDelegate> delegate;
-(CGSize)sizeThatFits:(CGSize)fits;
@end

