/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class NSMutableArray, UITableView, SBAssistantGuideDomainModel;

@interface SBAssistantGuideSectionListController : XXUnknownSuperclass <UITableViewDelegate, UITableViewDataSource> {
	UITableView* _tableView;
	SBAssistantGuideDomainModel* _currentDomain;
	NSMutableArray* _cells;
}
@property(retain, nonatomic) SBAssistantGuideDomainModel* currentDomain;
@property(readonly, assign, nonatomic) UITableView* tableView;
-(id)initWithView:(id)view;
-(void)dealloc;
-(void)_reloadCellsForCurrentDomain;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
@end

