/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBAssistantGuideDomainListCellDelegate <NSObject>
-(void)guideDomainCell:(id)cell didHighlight:(BOOL)highlight;
@end

