/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

@interface SBAssistantGuideSectionHeaderCell : XXUnknownSuperclass {
	UILabel* _label;
}
-(id)initWithReuseIdentifier:(id)reuseIdentifier;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setText:(id)text;
-(CGSize)sizeThatFits:(CGSize)fits;
@end

