/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBAssistantViewDelegate <NSObject>
-(void)assistantViewSearchScrolledToView:(id)view;
-(void)assistantView:(id)view madeRequest:(id)request;
-(void)assistantViewAnimatedIn:(id)anIn;
-(void)assistantViewAnimatedOut:(id)anOut;
-(float)assistantViewAudioLevel:(id)level;
-(BOOL)assistantViewAffectsMagicPocket:(int)pocket;
@end

