/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBAssistantEducationAlertItem, NSMutableSet, NSString, NSTimer;

@interface SBAssistantEducationAlertManager : XXUnknownSuperclass {
	int _syncFinishedToken;
	id _unlockHandler;
	NSTimer* _unlockTimer;
	BOOL _userHasBeenEducated;
	BOOL _waitingOnUserDataSync;
	BOOL _assistantSupported;
	BOOL _dictationSupported;
	BOOL _assistantHasBeenActivated;
	NSString* _syncDidFinishLanguage;
	NSMutableSet* _newlyAvailableLanguages;
	int _type;
	NSString* _language;
	SBAssistantEducationAlertItem* _item;
}
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)_invalidate;
-(void)_setEducated;
-(void)_showEducationAlert;
-(void)_startUnlockTimer;
-(void)_clearUnlockTimer;
-(void)_unlockTimerFired:(id)fired;
-(void)_afSyncDidFinish;
-(void)_languageActivated:(id)activated;
-(id)_currentAssistantLanguage;
-(BOOL)_availableForLanguage:(id)language;
-(BOOL)_availableForCurrentLanguage;
-(BOOL)_shouldAcceptNewLanguage:(id)language;
-(void)_assistantActivationChanged:(id)changed;
-(BOOL)_shouldShowReadyForLanguageCode:(id)languageCode;
-(void)_calculateTypeAndLanguage;
-(void)_waitForUnlockToDisplayAlert;
-(void)educationAlertWasDeactivated:(id)deactivated;
@end

