/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDismissOnlyAlertItem.h"

@protocol SBAssistantEducationAlertItemDelegate;

@interface SBAssistantEducationAlertItem : SBDismissOnlyAlertItem {
	id<SBAssistantEducationAlertItemDelegate> _delegate;
}
@property(assign, nonatomic) id<SBAssistantEducationAlertItemDelegate> delegate;
-(id)initWithType:(int)type language:(id)language delegate:(id)delegate;
-(void)dealloc;
-(void)didDeactivateForReason:(int)reason;
-(void)_assistantActivationChanged:(id)changed;
@end

