/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIImageView, UILabel;

@interface SBAssistantUnavailableView : XXUnknownSuperclass {
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
	UIImageView* _embossedMic;
}
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)layoutSubviews;
@end

