/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSArray;

@interface SBAssistantUserUtterance : XXUnknownSuperclass {
	NSMutableArray* _phrases;
	NSArray* _originalPhrases;
	id _correctionIdentifier;
	BOOL _openToInterpretation;
}
+(id)utteranceWithString:(id)string correctionIdentifier:(id)identifier;
-(id)init;
-(id)initWithPhrases:(id)phrases correctionIdentifier:(id)identifier;
-(id)initWithString:(id)string correctionIdentifier:(id)identifier;
-(void)dealloc;
-(id)description;
-(id)recursiveDescription;
-(id)phrases;
-(id)correctionIdentifier;
-(id)originalPhrases;
-(BOOL)openToInterpretation;
-(id)text;
@end

