/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UILabel;

@interface SBAssistantBasicView : XXUnknownSuperclass {
	UILabel* _title;
	UILabel* _subtitle;
}
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setTitleText:(id)text;
-(void)setSubtitleText:(id)text;
-(void)layoutSubviews;
@end

