/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBAssistantTableViewCellDelegate <NSObject>
-(void)assistantTableViewCellDidRemoveFromSuperview:(id)assistantTableViewCell;
@end

