/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBAssistantBasicView, NSDictionary;

@interface SBAssistantBasicViewController : XXUnknownSuperclass {
	NSDictionary* _properties;
	SBAssistantBasicView* _view;
}
-(id)initWithAceObject:(id)aceObject delegate:(id)delegate;
-(void)dealloc;
-(id)view;
@end

