/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSArray, NSString;

@interface SBAssistantGuideSectionModel : XXUnknownSuperclass {
	NSString* _title;
	NSMutableArray* _phrases;
}
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) NSArray* phrases;
-(id)init;
-(void)dealloc;
@end

