/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "SBAssistantGuideDomainListCellDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UITableView, UIImageView, NSMutableArray, SBAssistantGuideModel;
@protocol SBAssistantGuideDomainListDelegate;

@interface SBAssistantGuideDomainListController : XXUnknownSuperclass <UITableViewDelegate, UITableViewDataSource, SBAssistantGuideDomainListCellDelegate> {
	id<SBAssistantGuideDomainListDelegate> _delegate;
	UITableView* _tableView;
	UIImageView* _selectedOverlay;
	NSMutableArray* _filteredDomainIndices;
	SBAssistantGuideModel* _model;
}
@property(readonly, assign, nonatomic) UITableView* tableView;
@property(assign, nonatomic) id<SBAssistantGuideDomainListDelegate> delegate;
-(id)initWithModel:(id)model view:(id)view;
-(void)dealloc;
-(void)updateDomainList;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)guideDomainCell:(id)cell didHighlight:(BOOL)highlight;
@end

