/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBFloatingAlertGrabberDelegate.h"
#import "BBObserverDelegate.h"
#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"

@class SBAwayListUnlockActionContext, UIView, SBAwayBulletinCell, SBAwayBulletinListView, NSArray, BBObserver, NSMutableArray;

@interface SBAwayBulletinListController : XXUnknownSuperclass <BBObserverDelegate, UITableViewDataSource, UITableViewDelegate, SBFloatingAlertGrabberDelegate> {
	BBObserver* _observer;
	NSMutableArray* _listItems;
	NSMutableArray* _realertTimers;
	SBAwayBulletinCell* _unlockingCell;
	BOOL _lockBarIsTracking;
	SBAwayBulletinCell* _trackingCell;
	SBAwayBulletinListView* _view;
	CGRect _viewRect;
	float _contentHeight;
	BOOL _dimmed;
	BOOL _presentingNewBulletin;
	BOOL _dimmingForLockButtonPress;
	BOOL _hibernating;
	CGAffineTransform _pinnedViewTransform;
	SBAwayListUnlockActionContext* _unlockActionContext;
	NSMutableArray* _pendingSystemAlerts;
	id _itemToBlink;
	id _itemToFloat;
}
@property(readonly, assign, nonatomic) UIView* view;
@property(assign, nonatomic) BOOL dimmed;
@property(assign, nonatomic) CGRect viewRect;
@property(readonly, assign, nonatomic) BOOL lockBarIsTracking;
@property(readonly, assign, nonatomic) NSArray* listItems;
@property(readonly, assign, nonatomic) BOOL presentingNewBulletin;
-(id)init;
-(void)dealloc;
-(void)clearViewsAndHibernate;
-(void)rebuildViewsAndStopHibernating;
-(BOOL)isHibernating;
-(void)setUnlockActionContext:(id)context;
-(void)showTestBulletin;
-(id)_listItemForNewBulletin:(id)newBulletin;
-(id)_listItemContainingBulletinID:(id)anId;
-(id)_systemAlertItem;
-(void)_sortListItems;
-(id)unlockActionContext;
-(void)setTableItemToBlink:(id)blink;
-(void)grabEnded;
-(void)setTableItemToFloat:(id)aFloat force:(BOOL)force;
-(void)setTableItemToFloat:(id)aFloat;
-(void)_awayControllerRelocked:(id)relocked;
-(void)setUnlockingTableViewCell:(id)cell;
-(void)lockBarStartedTrackingForCell:(id)cell;
-(void)lockBarStoppedTracking;
-(void)resetLockBarIfTracking;
-(void)_alertForBulletin:(id)bulletin;
-(void)_realertTimerFired:(id)fired;
-(void)_killRealerts:(id)realerts;
-(void)_scheduleRealerts:(id)realerts;
-(void)_hardwareButtonPressed:(id)pressed;
-(int)_rowAnimationForInsert;
-(int)_rowAnimationForDelete;
-(void)_updateModelAndTableViewForAddition:(id)addition;
-(void)_updateModelAndTableViewForModification:(id)modification originalHeight:(float)height;
-(void)_updateModelAndTableViewForRemoval:(id)removal originalHeight:(float)height;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
-(void)observer:(id)observer modifyBulletin:(id)bulletin;
-(void)observer:(id)observer removeBulletin:(id)bulletin;
-(BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)observer;
-(id)observer:(id)observer multipleThumbnailSizeConstraintsForAttachmentType:(int)attachmentType;
-(id)observer:(id)observer composedAttachmentImageForType:(int)type thumbnailData:(id)data key:(id)key;
-(void)activateAlertItem:(id)item didUndimScreen:(BOOL)screen;
-(void)deactivateAlertItem:(id)item;
-(id)pendOrDeactivateAlertItemsForUnlock;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)_setContentForTableCell:(id)tableCell withItem:(id)item floating:(BOOL)floating;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(double)animationDelayForShowPasscodeUI:(BOOL)showPasscodeUI duration:(double)duration;
-(double)animationDurationForShowPasscodeUI:(BOOL)showPasscodeUI duration:(double)duration;
-(void)setViewHiddenForUnlock:(BOOL)unlock;
-(void)setViewHiddenForUnlock:(BOOL)unlock force:(BOOL)force;
-(void)setPinnedViewTransform:(CGAffineTransform)transform;
-(void)_configureAndPositionView;
-(float)_rowHeightForItem:(id)item floating:(BOOL)floating;
@end

