/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class NSMutableDictionary, UIButton, UIView;

@interface SBAwayLockBar : XXUnknownSuperclass {
	UIButton* _slideshowButton;
	UIButton* _cameraButton;
	UIView* _cameraGrabber;
	NSMutableDictionary* _orientationToButtonImages;
}
-(void)dealloc;
-(float)knobTrackInsetLeft;
-(void)setLabel:(id)label;
-(BOOL)_shouldStopLabelAnimationForGrab;
-(void)setShowsSlideshowButton:(BOOL)button;
-(void)setSlideshowButtonSelected:(BOOL)selected;
-(void)setShowsCameraButton:(BOOL)button;
-(void)setShowsCameraGrabber:(BOOL)grabber;
-(BOOL)showsCameraGrabber;
-(void)setOrientation:(int)orientation;
-(id)_newButtonWithAction:(SEL)action tag:(int)tag hasComposedImage:(BOOL)image;
-(id)_unselectedImageForButtonTag:(int)buttonTag interfaceOrientation:(int)orientation;
-(id)_selectedImageForButtonTag:(int)buttonTag interfaceOrientation:(int)orientation;
-(void)_setImagesForButton:(id)button orientation:(int)orientation;
-(void)_setShowsButton:(BOOL)button button:(id*)button2 buttonTag:(int)tag hasComposedImage:(BOOL)image action:(SEL)action animated:(BOOL)animated;
-(void)_slideshowButtonActivated:(id)activated;
-(void)_cameraButtonHit:(id)hit;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
@end

