/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UITableView, UIView;
@protocol SBFloatingAlertGrabberDelegate;

@interface SBAwayBulletinListView : XXUnknownSuperclass {
	UITableView* _tableView;
	UIView* _tableContainerView;
	UIView* _tableBackgroundView;
	UIView* _tableTopFadeOverlay;
	UIView* _tableBottomFadeOverlay;
	UITableView* _firstAlertTableView;
	UIView* _firstAlertBGView;
	float _firstAlertTableHeight;
	UIView* _tableGrabberView;
	int _normalViewStyle;
	float _normalTableHeight;
	id<SBFloatingAlertGrabberDelegate> _grabDelegate;
	int _viewStyle;
	BOOL _hiddenForUnlock;
}
@property(readonly, assign, nonatomic) UITableView* tableView;
@property(readonly, assign, nonatomic) int viewStyle;
@property(readonly, assign, nonatomic) UITableView* firstAlertTableView;
@property(assign, nonatomic) float firstAlertTableHeight;
@property(assign, nonatomic) id<SBFloatingAlertGrabberDelegate> grabDelegate;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setFrame:(CGRect)frame;
-(float)_translationDistanceForGrabber;
-(void)_grabStarted;
-(void)_grabChanged:(float)changed;
-(void)_grabEnded;
-(void)setViewStyle:(int)style withFloatingAlert:(BOOL)floatingAlert andTableHeight:(float)height;
-(CGAffineTransform)_slideOutTransform;
-(BOOL)shouldHideBySlidingOut;
-(void)setHiddenForUnlock:(BOOL)unlock force:(BOOL)force;
-(float)tableContainerHeightForContentHeight:(float)contentHeight;
-(void)lockBarStartedTracking;
-(void)lockBarStoppedTracking;
-(void)layoutSubviews;
-(BOOL)floatingAlertNeedsMainUnlockAction;
-(void)clearFloatingAlertButtonHandler;
-(id)_tableHeaderView;
-(id)_tableFooterView;
@end

