/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBulletinCellContentViewBase.h"


@interface SBAwayBulletinFloatingContentView : SBBulletinCellContentViewBase {
	BOOL _hasButton;
}
@property(assign, nonatomic) BOOL hasButton;
+(float)heightForBulletinStyleWithSubtitle:(id)subtitle message:(id)message maxLines:(unsigned)lines contentWidth:(float)width;
+(float)heightForBulletinStyleWithSubtitle:(id)subtitle message:(id)message maxLines:(unsigned)lines attachmentText:(id)text imageHeight:(float)height contentWidth:(float)width;
+(float)heightForSystemAlertStyleWithTitle:(id)title maxLines:(unsigned)lines message:(id)message maxLines:(unsigned)lines4 buttonHeight:(float)height contentWidth:(float)width;
-(id)_titleFont;
-(id)_subtitleFont;
-(id)_messageFont;
-(id)_attachmentFont;
-(id)_dateFont;
-(void)setTitle:(id)title;
-(void)setSubtitle:(id)subtitle;
-(void)setMessage:(id)message;
-(void)setStartDate:(id)date endDate:(id)date2 timeZone:(id)zone allDay:(BOOL)day formatStyle:(int)style;
-(void)setAttachmentImage:(id)image;
-(void)setAttachmentImageSize:(CGSize)size;
-(void)setAttachmentText:(id)text;
-(void)layoutSubviews;
-(void)_configureLabel:(id)label withFont:(id)font alignment:(int)alignment;
@end

