/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SUDescriptor;

@interface SBBaseSoftwareUpdateAlertItem : XXUnknownSuperclass {
	SUDescriptor* _descriptor;
}
@property(readonly, assign, nonatomic) SUDescriptor* descriptor;
-(id)initWithDescriptor:(id)descriptor;
-(void)dealloc;
-(id)updateName;
-(void)activateSoftwareUpdateSettingsDisplay;
-(void)activateDisplayWithURL:(id)url;
-(BOOL)forcesModalAlertAppearance;
-(BOOL)shouldShowInLockScreen;
-(BOOL)dismissOnLock;
@end

