/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIImageView, UIImage, UILabel;

@interface SBBatteryChargingView : XXUnknownSuperclass {
	int _type;
	UIImageView* _topBatteryView;
	UIImageView* _bottomBatteryView;
	UIImage* _lastBatteryImage;
	UILabel* _percentLabel;
	int _lastBatteryIndex;
	int _lastBatteryPercentage;
	unsigned _showReflection : 1;
}
+(CGSize)defaultSizeForType:(int)type;
+(float)batteryHeightForType:(int)type;
+(int)redChargeIndexForType:(int)type;
-(id)initWithFrame:(CGRect)frame type:(int)type;
-(void)dealloc;
-(void)setShowsReflection:(BOOL)reflection;
-(int)_currentBatteryIndex;
-(id)_imageFormatString;
-(void)_batteryStatusChanged:(id)changed;
@end

