/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView, UIView, SBBulletinBannerItem, UILabel;

@interface SBBannerView : XXUnknownSuperclass {
	SBBulletinBannerItem* _item;
	UIView* _iconView;
	UILabel* _titleLabel;
	UILabel* _messageLabel;
	float _imageWidth;
	UIImageView* _bannerView;
	UIView* _underlayView;
}
-(id)initWithItem:(id)item;
-(id)item;
-(void)dealloc;
-(void)_createSubviewsWithBannerImage:(id)bannerImage;
-(void)layoutSubviews;
-(id)_bannerMaskStretchedToWidth:(float)width;
-(id)_bannerImageWithAttachmentImage:(id)attachmentImage;
@end

