/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIImage;

@interface SBBatteryReflectionView : XXUnknownSuperclass {
	UIImage* _image;
	UIImage* _maskImage;
	float _bottomMargin;
}
-(id)initWithImage:(id)image bottomMargin:(float)margin;
-(void)dealloc;
-(void)setImage:(id)image;
-(void)drawRect:(CGRect)rect;
@end

