/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBHUDView.h"


@interface SBBrightnessHUDView : SBHUDView {
}
-(id)init;
-(BOOL)displaysLabel;
@end

