/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBulletinCellContentViewBase.h"


@interface SBBulletinCellContentView : SBBulletinCellContentViewBase {
	BOOL _italicizeContent;
	float _shadowBlur;
	BOOL _buttonsBelowContent;
}
+(id)_titleFont:(BOOL)font;
+(id)_dateFont:(BOOL)font;
+(id)_subtitleFont:(BOOL)font;
+(id)_messageFont:(BOOL)font;
+(id)_attachmentFont:(BOOL)font;
+(float)heightForBulletinStyleWithSubtitle:(id)subtitle message:(id)message maxLines:(unsigned)lines contentWidth:(float)width italicize:(BOOL)italicize;
+(float)heightForBulletinStyleWithSubtitle:(id)subtitle imageHeight:(float)height italicize:(BOOL)italicize;
+(float)heightForSystemAlertStyleWithTitle:(id)title maxLines:(unsigned)lines message:(id)message maxLines:(unsigned)lines4 contentWidth:(float)width;
-(void)setItalicizesContent:(BOOL)content;
-(void)setShadowBlur:(float)blur;
-(void)setHasButtonBelow:(BOOL)below;
-(id)_initForLayoutStyle:(int)layoutStyle;
-(void)_configureLabel:(id)label withFont:(id)font alignment:(int)alignment;
-(id)_dateFont;
-(id)_titleFont;
-(id)_subtitleFont;
-(id)_messageFont;
-(id)_attachmentFont;
-(BOOL)_shouldVerticallyCenterBulletinStyleTitleAndDate;
-(float)_layoutTitleAtX:(float)x y:(float)y;
-(float)_layoutSubtitleAtX:(float)x y:(float)y;
-(float)_layoutAttachmentImageAtX:(float)x y:(float)y;
-(float)_layoutMessageAtX:(float)x y:(float)y;
-(void)_layoutAttachmentTextAtX:(float)x;
-(void)layoutSubviews;
-(void)_drawLabel:(id)label inContext:(CGContextRef)context;
-(void)drawRect:(CGRect)rect;
@end

