/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDismissOnlyAlertItem.h"


@interface SBBuddyLockScreenDismissOnlyAlertItem : SBDismissOnlyAlertItem {
}
-(BOOL)allowInSetup;
-(BOOL)forcesModalAlertAppearance;
@end

