/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIImageView;

@interface SBBulletinCellSelectionView : XXUnknownSuperclass {
	UIImageView* _gradientView;
	float _cellSeparatorHeight;
}
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setCellSeparatorHeight:(float)height;
-(void)layoutSubviews;
@end

