/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSMutableArray, BBBulletin, AVController, BBObserver;

@interface SBBulletinSoundController : XXUnknownSuperclass {
	BBObserver* _observer;
	BOOL _deviceIsLocked;
	BOOL _assistantIsVisible;
	NSMutableArray* _blockQueue;
	BBBulletin* _ringtoneBulletin;
	AVController* _ringtoneController;
	id _ringtoneObserver;
	NSMutableDictionary* _clientsBySoundIDs;
}
+(id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;
+(id)sharedInstance;
+(id)sharedInstanceIfExists;
-(id)init;
-(void)_cleanupSystemSound:(unsigned long)sound andKill:(BOOL)kill;
-(void)_killSystemSound:(unsigned long)sound;
-(void)_killRingtone;
-(void)_hardwareButtonPressed:(id)pressed;
-(BOOL)handleVolumeButtonDownEvent;
-(BOOL)playSoundForBulletin:(id)bulletin;
-(void)killSoundForBulletin:(id)bulletin;
-(BOOL)playSystemAlertSound:(unsigned long)sound forBundleID:(id)bundleID;
-(void)killSounds;
-(void)_enqueueBlock:(id)block;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
-(void)observer:(id)observer removeBulletin:(id)bulletin;
-(void)bulletinWindowStoppedBeingBusy;
@end

