/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBBulletinLockBar : XXUnknownSuperclass {
}
-(id)initWithFrame:(CGRect)frame knobImage:(id)image;
-(void)dealloc;
-(float)defaultWellWidth;
-(id)wellImageName;
-(BOOL)allowsTouchTrackingBeyondVerticalThreshold;
-(BOOL)usesBackgroundImage;
-(BOOL)_shouldStopLabelAnimationForGrab;
-(float)knobTrackInsetLeft;
-(float)knobTrackInsetRight;
-(void)_adjustLabelOrigin;
-(float)_calcKnobYOffset;
-(void)knobDragged:(float)dragged;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)showKnob;
-(void)hideKnob;
-(void)setAlpha:(float)alpha;
-(void)setWellWidth:(float)width;
@end

