/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBBulletinLinenBackedCell : XXUnknownSuperclass {
}
-(id)initWithLinenView:(id)linenView reuseIdentifier:(id)identifier;
-(void)adjustLinenContents;
-(void)setLinenGradientAlpha:(float)alpha;
-(void)setFrame:(CGRect)frame;
@end

