/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class SBBulletinBlurredShadowLabel, SBBulletinListTouchEater, UIImageView, SBBulletinTableView, UIView, UIStatusBar;

@interface SBBulletinListView : XXUnknownSuperclass {
	int _orientation;
	float _currentY;
	UIView* _slidingView;
	UIImageView* _linenView;
	CGSize _linenSize;
	SBBulletinTableView* _tableView;
	UIStatusBar* _statusBar;
	UIView* _statusBarPocket;
	UIView* _grabber;
	SBBulletinBlurredShadowLabel* _noNotificationsLabel;
	SBBulletinListTouchEater* _clearButtonTouchEater;
	UIView* _cornerView[4];
	UIView* _bottomShadowView;
	UIView* _linenMask;
	UIView* _linenGradient;
	UIView* _linenRim;
	UIView* _linenContainer;
	UIView* _wholeShadowView;
	UIView* _sideShadowView[2];
	float _tableViewContentHeight;
}
+(id)linen;
+(id)_pathToLinenCache;
+(void)removeCachedLinen;
+(void)loadLinen;
-(id)initWithFrame:(CGRect)frame delegate:(id)delegate;
-(void)dealloc;
-(id)tableView;
-(id)linenView;
-(float)linenGradientAlpha;
-(void)positionSlidingViewAtY:(float)y;
-(float)onscreenY;
-(float)offscreenY;
-(float)currentY;
-(void)setBottomCornersOffscreen:(BOOL)offscreen animated:(BOOL)animated;
-(void)setCornerAlpha:(float)alpha;
-(void)setBottomShadowAlpha:(float)alpha;
-(void)_positionNoNotificationsLabel;
-(void)setShowsNoNotificationsLabel:(BOOL)label animated:(BOOL)animated;
-(CGRect)slidingViewFrame;
-(id)slidingView;
-(id)clearButtonTouchEater;
-(void)handleStatusBarTap:(id)tap;
-(void)handleTableViewOffsetChange;
-(void)layoutForOrientation:(int)orientation;
-(void)_ensureContentHeightHasBeenComputed;
-(float)_iPadSlidingViewHeightInOrientation:(int)orientation;
-(float)_linenGradientAlphaForHeight:(float)height;
-(void)adjustLayoutForAnimatedTableViewContentHeightChange:(float)animatedTableViewContentHeightChange;
-(void)adjustLayoutForTableViewReload;
-(void)willRotateToOrientation:(int)orientation;
-(void)didRotateFromOrientation:(int)orientation;
@end

