/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class CALayer;

@interface SBBuddyLogoZoomView : XXUnknownSuperclass {
	CALayer* _contentLayer;
	id _animationCompleteBlock;
}
-(id)initWithFrame:(CGRect)frame;
-(void)startAnimationWithCompletionBlock:(id)completionBlock;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
@end

