/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBulletinLinenSegmentView.h"

@class SBBulletinClearButton, SBBulletinBlurredShadowLabel, NSString, UIView;
@protocol SBBulletinHeaderViewDelegate;

@interface SBBulletinHeaderView : SBBulletinLinenSegmentView {
	UIView* _translucentOverlay;
	UIView* _iconView;
	SBBulletinBlurredShadowLabel* _sectionLabel;
	SBBulletinClearButton* _clearButton;
	id<SBBulletinHeaderViewDelegate> _delegate;
	NSString* _sectionID;
}
@property(assign, nonatomic) id<SBBulletinHeaderViewDelegate> delegate;
@property(retain, nonatomic) NSString* sectionID;
@property(readonly, assign, nonatomic) SBBulletinClearButton* clearButton;
+(float)headerHeight;
-(id)initWithFrame:(CGRect)frame linenView:(id)view;
-(void)dealloc;
-(void)setShowsClearButton:(BOOL)button animated:(BOOL)animated;
-(void)layoutSubviews;
-(void)willMoveToWindow:(id)window;
-(id)_sectionNameForSectionID:(id)sectionID;
-(id)_newIconViewForSectionID:(id)sectionID;
@end

