/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBulletinWindowClient.h"
#import "UIGestureRecognizerDelegate.h"
#import "SBBulletinBusyClient.h"
#import "BBObserverDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, SBBannerAndShadowView, BBObserver, UIView, NSMutableArray;

@interface SBBulletinBannerController : XXUnknownSuperclass <BBObserverDelegate, SBBulletinWindowClient, SBBulletinBusyClient, UIGestureRecognizerDelegate> {
	BBObserver* _observer;
	NSMutableArray* _incomingBulletinQueue;
	SBBannerAndShadowView* _bannerAndShadowView;
	UIView* _snapshotView;
	BOOL _dismissalOverdue;
	BOOL _replaceDelayIsActive;
	BOOL _soundIsPlaying;
	BOOL _assistantIsVisible;
	BOOL _inhospitableDisplayIsFrontmost;
	BOOL _deviceIsLocked;
	NSMutableSet* _sectionIDsToPend;
	float _showcaseHeight;
}
+(id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;
+(id)sharedInstance;
+(id)sharedInstanceIfExists;
-(id)init;
-(void)dealloc;
-(BOOL)isShowingBanner;
-(void)showTestBanner;
-(void)dismissBanner;
-(void)dismissBannerWithAnimation:(int)animation;
-(void)setBannerAlpha:(float)alpha;
-(id)newBannerSnapshotViewRotatedForOrientation:(int)orientation;
-(void)adjustLayoutForShowcaseHeight:(float)showcaseHeight;
-(unsigned)_indexOfIncomingBulletinID:(id)incomingBulletinID;
-(void)_removeEnqueuedBulletin:(id)bulletin;
-(BOOL)_replaceEnqueuedBulletin:(id)bulletin;
-(void)_enqueueBulletin:(id)bulletin;
-(void)_dequeueBulletinIfPossible;
-(void)_presentBannerForItem:(id)item;
-(void)_setBannerTranslation:(float)translation progress:(float)progress;
-(float)_progressForBannerTranslation:(float)bannerTranslation maxTranslation:(float)translation;
-(void)_adjustShadowAlphasForProgress:(float)progress;
-(void)_handleBannerPanGesture:(id)gesture;
-(void)_handleBannerTapGesture:(id)gesture;
-(void)_tryToDismissBannerWithAnimation:(int)animation;
-(void)_dismissIntervalElapsed;
-(void)_replaceIntervalElapsed;
-(void)_bulletinSoundCompleted:(id)completed;
-(void)_stopCurrentSound;
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(void)bulletinWindowWillRotateToOrientation:(int)bulletinWindow;
-(void)bulletinWindowIsAnimatingRotationToOrientation:(int)orientation;
-(void)bulletinWindowDidRotateFromOrientation:(int)bulletinWindow;
-(void)bulletinWindowStoppedBeingBusy;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
-(void)observer:(id)observer modifyBulletin:(id)bulletin;
-(void)observer:(id)observer removeBulletin:(id)bulletin;
-(void)observer:(id)observer updateSectionInfo:(id)info;
-(BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)observer;
-(id)observer:(id)observer thumbnailSizeConstraintsForAttachmentType:(int)attachmentType;
-(id)observer:(id)observer composedAttachmentImageForType:(int)type thumbnailData:(id)data key:(id)key;
-(id)_dequeueNextBulletinItem;
-(CGRect)_normalBannerFrameForOrientation:(int)orientation;
-(CGRect)_currentBannerFrameForOrientation:(int)orientation;
-(CGRect)_calculateFlipRectAndCreateSnapshotViewForBannerFrame:(CGRect)bannerFrame orientation:(int)orientation;
-(void)_setUpPerspectiveForNormalFlipRect:(CGRect)normalFlipRect;
-(void)_removePerspective;
-(void)_tearDownView;
-(void)_flipToBanner:(id)banner animation:(int)animation;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(id)_meshTransformForDegreesOfRotation:(float)rotation flipInsets:(UIEdgeInsets)insets orientation:(int)orientation topIsLive:(BOOL)live;
@end

