/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UIGestureRecognizerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBBulletinListTouchEater : XXUnknownSuperclass <UIGestureRecognizerDelegate> {
}
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(BOOL)canBePreventedByGestureRecognizer:(id)recognizer;
@end

