/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBBulletinDateLabel <NSObject>
@property(assign, nonatomic, getter=isAllDay) BOOL allDay;
-(void)setStartDate:(id)date withTimeZone:(id)timeZone;
-(void)setEndDate:(id)date withTimeZone:(id)timeZone;
@end

