/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class BBBulletin, NSArray;

@interface SBBulletinBannerItem : XXUnknownSuperclass {
	BBBulletin* _seedBulletin;
	NSArray* _additionalBulletins;
}
+(id)itemWithBulletin:(id)bulletin;
+(id)itemWithSeedBulletin:(id)seedBulletin additionalBulletins:(id)bulletins;
-(id)_initWithSeedBulletin:(id)seedBulletin additionalBulletins:(id)bulletins;
-(void)dealloc;
-(id)attachmentImage;
-(id)iconImage;
-(id)_appName;
-(id)title;
-(id)message;
-(id)attachmentText;
-(BOOL)playSound;
-(void)killSound;
-(void)sendResponse;
-(id)launchBlock;
-(id)seedBulletin;
@end

