/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "BBObserverDelegate.h"
#import "SBBulletinWindowClient.h"
#import "SBBulletinListViewDelegate.h"
#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBApplication, SBBulletinClearButton, NSTimer, NSMutableDictionary, NSArray, BBObserver, SBBulletinListTabView, SBBulletinListView, NSMutableArray;

@interface SBBulletinListController : XXUnknownSuperclass <BBObserverDelegate, SBBulletinListViewDelegate, SBBulletinWindowClient> {
	BBObserver* _observer;
	NSMutableDictionary* _enabledSectionsByID;
	NSMutableArray* _visibleSectionIDs;
	NSArray* _possibleSectionIDs;
	unsigned _sectionOrderRule;
	NSMutableArray* _weeApps;
	NSMutableDictionary* _headerViewsBySectionID;
	SBBulletinListTabView* _tabView;
	SBBulletinListView* _listView;
	BOOL _listViewTableViewHasLoaded;
	BOOL _listViewIsActive;
	BOOL _weeAppFullViewsHaveBeenLoaded;
	SBApplication* _coveredApplication;
	SBBulletinClearButton* _clearButtonCurrentlyInClearState;
	NSMutableArray* _enqueuedUpdates;
	BOOL _grabbed;
	float _grabbedY;
	BOOL _pullingDownOutsideList;
	float _showcaseOffset;
	NSTimer* _weeAppSnapshotTimer;
}
+(id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;
+(id)sharedInstance;
+(id)sharedInstanceIfExists;
-(id)init;
-(void)dealloc;
-(id)listView;
-(float)listViewHeight;
-(void)showTabViewAnimated:(BOOL)animated;
-(void)hideTabViewAnimated:(BOOL)animated;
-(BOOL)isShowingTabView;
-(void)prepareToShowListViewAnimated:(BOOL)showListViewAnimated aboveBanner:(BOOL)banner;
-(void)prepareToHideListViewAnimated:(BOOL)hideListViewAnimated;
-(void)_positionTabViewAtY:(float)y;
-(void)positionListViewAtY:(float)y;
-(void)setListViewBottomShadowAlpha:(float)alpha;
-(void)_cleanupAfterShowListView;
-(void)_cleanupAfterHideListView;
-(void)_finishShowingListViewAnimated:(BOOL)animated;
-(void)finishShowingListView;
-(void)showListViewAnimated:(BOOL)animated;
-(void)hideListViewAnimated:(BOOL)animated;
-(id)_dynamicAnimationForShow:(BOOL)show targetValue:(double)value withInitialVelocity:(double)initialVelocity extraPull:(BOOL)pull;
-(void)showListViewWithInitialVelocity:(float)initialVelocity additionalValueApplier:(id)applier completion:(id)completion;
-(void)hideListViewWithInitialVelocity:(float)initialVelocity hiddenY:(float)y extraPull:(BOOL)pull additionalValueApplier:(id)applier completion:(id)completion;
-(void)hideListViewWithInitialVelocity:(float)initialVelocity completion:(id)completion;
-(void)showListViewWithInitialVelocity:(float)initialVelocity completion:(id)completion;
-(void)_setListViewActive:(BOOL)active;
-(void)adjustViewForShowcaseOffset:(float)showcaseOffset;
-(void)_clearSnapshotTimer;
-(void)_clearWeeAppSnapshots;
-(void)_snapshotTimerFired;
-(void)_tearDownListView;
-(void)_tearDownTabView;
-(BOOL)listViewIsActive;
-(void)_sortVisibleSectionIDsForManualSortOrder;
-(void)_sortVisibleSectionIDsForAutomaticSortOrder;
-(void)_sortVisibleSectionIDs;
-(unsigned)_insertVisibleSectionIDForManualSortOrder:(id)manualSortOrder;
-(unsigned)_insertVisibleSectionIDForAutomaticSortOrder:(id)automaticSortOrder;
-(unsigned)_insertVisibleSectionID:(id)anId;
-(id)_weeAppForSectionID:(id)sectionID;
-(void)_removeWeeAppForSectionID:(id)sectionID;
-(id)_weeAppForSectionID:(id)sectionID bundlePath:(id)path;
-(BOOL)_canPerformUpdate;
-(void)_performOrEnqueueUpdate:(id)update;
-(void)_performEnqueuedUpdates;
-(void)_loadSections;
-(void)_reloadTableView;
-(void)_configureForChangedContentAnimated:(BOOL)changedContentAnimated;
-(id)_sectionAtIndex:(unsigned)index;
-(id)_bulletinAtIndexPath:(id)indexPath;
-(id)_indexPathForBulletin:(id)bulletin;
-(float)_rowHeightForBulletin:(id)bulletin;
-(float)_headerHeightForSection:(id)section;
-(void)_clearSection:(id)section;
-(void)_handleUngrabWithVelocity:(CGPoint)velocity completion:(id)completion;
-(void)_updateForTouchBeganOrMovedWithLocation:(CGPoint)location velocity:(CGPoint)velocity;
-(void)_updateForTouchEndedWithVelocity:(CGPoint)velocity completion:(id)completion;
-(void)_updateForTouchCanceled;
-(void)handleShowNotificationsGestureBeganWithTouchLocation:(CGPoint)touchLocation;
-(void)handleShowNotificationsGestureChangedWithTouchLocation:(CGPoint)touchLocation velocity:(CGPoint)velocity;
-(void)handleShowNotificationsGestureEndedWithVelocity:(CGPoint)velocity completion:(id)completion;
-(void)handleShowNotificationsGestureCanceled;
-(void)handleTap:(id)tap;
-(void)handlePan:(id)pan;
-(void)handleEatenTouch:(id)touch;
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
-(void)_setClearButtonCurrentlyInClearState:(id)clearState;
-(void)bulletinWindowWillRotateToOrientation:(int)bulletinWindow;
-(void)bulletinWindowIsAnimatingRotationToOrientation:(int)orientation;
-(void)bulletinWindowDidRotateFromOrientation:(int)bulletinWindow;
-(void)_updateModelAndTableViewForNewSectionOrderRule:(unsigned)newSectionOrderRule;
-(void)_updateModelAndTableViewForNewSectionOrder:(id)newSectionOrder;
-(void)_updateModelAndTableViewForNewSectionInfo:(id)newSectionInfo;
-(void)_fixCellSeparatorAboveRow:(unsigned)row inSection:(id)section sectionIndex:(unsigned)index;
-(void)_fixLastRowSeparatorsAndWeeAppTopPaddingInAllSections;
-(void)_updateModelAndTableViewForAddition:(id)addition;
-(void)_updateModelAndTableViewForModification:(id)modification originalIndex:(unsigned)index;
-(void)_updateModelAndTableViewForRemoval:(id)removal originalIndex:(unsigned)index;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
-(void)observer:(id)observer modifyBulletin:(id)bulletin;
-(void)observer:(id)observer removeBulletin:(id)bulletin;
-(void)observer:(id)observer updateSectionOrderRule:(unsigned)rule;
-(void)observer:(id)observer updateSectionOrder:(id)order;
-(void)observer:(id)observer updateSectionInfo:(id)info;
-(BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)observer;
-(BOOL)observerShouldFetchAttachmentSizeBeforeBulletinDelivery:(id)observer;
-(id)observer:(id)observer thumbnailSizeConstraintsForAttachmentType:(int)attachmentType;
-(id)observer:(id)observer composedAttachmentImageForType:(int)type thumbnailData:(id)data key:(id)key;
-(CGSize)observer:(id)observer composedAttachmentSizeForType:(int)type thumbnailWidth:(float)width height:(float)height key:(id)key;
-(int)numberOfSectionsInTableView:(id)tableView;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)_separatorStyleForRow:(unsigned)row inSection:(id)section sectionIndex:(unsigned)index;
-(id)_bulletinCellForSection:(id)section sectionIndex:(unsigned)index row:(unsigned)row tableView:(id)view;
-(BOOL)_useTopPaddingForWeeAppAtSectionIndex:(unsigned)sectionIndex;
-(id)_weeAppCellForSection:(id)section sectionIndex:(unsigned)index tableView:(id)view;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)tableViewDidFinishReload:(id)tableView;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(void)scrollViewDidEndDecelerating:(id)scrollView;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)runScrollTest:(id)test iterations:(int)iterations delta:(int)delta;
-(void)finishedScrollTest;
@end

