/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBBulletinWindow : XXUnknownSuperclass {
}
-(id)hitTest:(CGPoint)test withEvent:(id)event;
@end

