/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, UIWindow;

@interface SBBulletinWindowController : XXUnknownSuperclass {
	UIWindow* _bulletinWindow;
	int _bulletinWindowOrientation;
	NSMutableSet* _windowClients;
	NSMutableSet* _busyClients;
	NSMutableSet* _busyReasons;
}
@property(readonly, assign, nonatomic) UIWindow* window;
@property(readonly, assign, nonatomic) int windowOrientation;
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)setBusy:(BOOL)busy forReason:(id)reason;
-(BOOL)isBusy;
-(BOOL)allowsShowNotificationsGesture;
-(BOOL)allowsHideNotificationsGesture;
-(BOOL)allowsDismissBannerGesture;
-(void)addWindowClient:(id)client;
-(void)removeWindowClient:(id)client;
-(void)addBusyClient:(id)client;
-(void)removeBusyClient:(id)client;
-(void)updateBulletinWindowOrientation;
-(void)setBulletinWindowOrientation:(int)orientation duration:(double)duration;
-(void)prepareToRotateToOrientation:(int)orientation;
-(void)rotateToOrientation:(int)orientation;
-(void)cleanUpAfterRotatingFromOrientation:(int)orientation;
-(void)_setWindowOrientation:(int)orientation;
@end

