/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDismissOnlyAlertItem.h"


@interface SBCarrierDebuggingAlert : SBDismissOnlyAlertItem {
}
+(BOOL)haveShownAlert;
-(void)didDeactivateForReason:(int)reason;
@end

