/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, SBApplication;

@interface SBCallPermissionAlertItem : XXUnknownSuperclass {
	NSURL* _url;
	SBApplication* _sender;
}
-(id)initWithURL:(id)url;
-(id)initWithURL:(id)url sender:(id)sender;
-(void)dealloc;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(BOOL)shouldShowInLockScreen;
-(BOOL)dismissOnLock;
-(BOOL)allowMenuButtonDismissal;
@end

