/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBSlidingAlertDisplay.h"


@interface SBCallFailureAlertDisplay : SBSlidingAlertDisplay {
}
+(id)newTopBarForInstance:(id)instance;
+(id)newBottomBarForInstance:(id)instance;
-(void)ignore:(id)ignore;
-(void)callBack:(id)back;
-(void)setAlert:(id)alert;
@end

