/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class CALayerHost;

@interface SBContext : XXUnknownSuperclass {
	unsigned _contextId;
	float _windowLevel;
	BOOL _hidden;
	BOOL _orderOutPending;
	CALayerHost* _layerHost;
}
@property(assign, nonatomic) unsigned contextId;
@property(assign, nonatomic) float windowLevel;
@property(assign, nonatomic, getter=isHidden) BOOL hidden;
@property(retain, nonatomic) CALayerHost* layerHost;
@property(assign, nonatomic, getter=isOrderOutPending) BOOL orderOutPending;
-(void)dealloc;
-(id)description;
@end

