/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

@interface SBCompassRecalibrationController : XXUnknownSuperclass {
	NSMutableArray* _assertionPorts;
}
+(id)sharedInstance;
-(void)dealloc;
-(BOOL)isCompassCalibrationHUDVisible;
-(void)showHUD;
-(void)removeHUD;
-(void)clientRequestedCompassHUD:(unsigned)hud;
-(void)_clientInvalidated:(CFMachPortRef)invalidated;
@end

