/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBCornerViewFactory : XXUnknownSuperclass {
}
+(id)newCornerViewForCorner:(int)corner cornersFrame:(CGRect)frame;
+(id)createCornerWindowForCorner:(int)corner windowLevel:(float)level cornersFrame:(CGRect)frame;
@end

