/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBPhraseInterpretation.h"

@class NSString;

@interface SBConstantInterpretation : SBPhraseInterpretation {
	NSString* _string;
}
-(id)initWithString:(id)string;
-(void)dealloc;
-(id)text;
@end

