/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDataPlanAlertItem.h"

@class NSString;

@interface SBDataPlanCompletionAlertItem : SBDataPlanAlertItem {
	NSString* _carrierName;
	BOOL _newAccount;
}
@property(copy, nonatomic) NSString* carrierName;
@property(assign, nonatomic, getter=isNewAccount) BOOL newAccount;
-(id)initWithCarrierName:(id)carrierName newAccount:(BOOL)account;
-(void)dealloc;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
@end

