/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDataPlanAccountAlertItem.h"


@interface SBDataPlanActivationAlertItem : SBDataPlanAccountAlertItem {
	BOOL _newAccount;
	BOOL _promptToDisable;
}
@property(assign, nonatomic, getter=isNewAccount) BOOL newAccount;
-(id)initWithAccountURL:(id)accountURL newAccount:(BOOL)account promptToDisable:(BOOL)disable;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
@end

