/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDeviceLockKeypad.h"
#import "SpringBoard-Structs.h"

@class UIButton, UIImage;

@interface SBDeviceLockKeypadPhone : SBDeviceLockKeypad {
	UIButton* _emergencyCallButton;
	UIButton* _poundButton;
	UIImage* _deleteIcon;
}
+(id)keypadImage;
+(id)pressedImage;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(float)_yFudge;
-(BOOL)showsEmergencyCallButton;
-(void)setShowsEmergencyCallButton:(BOOL)button;
-(void)setDeleteEnabled:(BOOL)enabled;
-(BOOL)deleteKeyChar;
-(BOOL)cancelKeyChar;
-(BOOL)emergencyKeyChar;
-(void)_updateCancelAndDeleteButtons;
@end

