/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDeviceLockViewWithKeypad.h"

@class UIView;

@interface SBDeviceLockViewWithKeypadWildcat : SBDeviceLockViewWithKeypad {
	UIView* _bottomContainer;
}
-(id)_initWithStyle:(int)style interfaceOrientation:(int)orientation showsEmergencyCall:(BOOL)call;
-(void)dealloc;
-(id)keypadView;
@end

