/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class SBDeviceLockViewWithKeyboard;

@interface SBDeviceLockKeyboard : XXUnknownSuperclass {
	SBDeviceLockViewWithKeyboard* _deviceLockView;
}
-(id)initWithFrame:(CGRect)frame deviceLockView:(id)view;
-(BOOL)canDismiss;
-(void)minimize;
-(void)maximize;
-(void)setMinimized:(BOOL)minimized;
-(BOOL)isMinimized;
@end

