/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDeviceLockTitle.h"

@class TPLCDView;

@interface SBDeviceLockTitlePhone : SBDeviceLockTitle {
	BOOL _highlighted;
	TPLCDView* _lcdView;
}
-(id)_initWithStyle:(int)style interfaceOrientation:(int)orientation;
-(void)dealloc;
-(BOOL)isHighlighted;
-(void)setHighlighted:(BOOL)highlighted;
-(id)title;
-(void)setTitle:(id)title;
-(id)subtitle;
-(void)setSubtitle:(id)subtitle;
-(void)blinkSubtitle;
@end

