/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBSlidingAlertDisplay.h"


@interface SBDeviceLockPasscodeEntryAlertDisplay : SBSlidingAlertDisplay {
}
-(void)useEmergencyCallButton;
-(void)deviceUnlockSucceeded;
-(void)deviceUnlockCanceled;
-(void)alertDisplayWillBecomeVisible;
-(void)dismiss;
-(float)delayForOthersActivation;
-(float)durationForOthersActivation;
@end

