/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBulletinDateLabel.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDate;

@interface SBDefaultDateLabel : XXUnknownSuperclass <SBBulletinDateLabel> {
	NSDate* _timeZoneRelativeStartDate;
	NSDate* _timeZoneRelativeEndDate;
	BOOL _allDay;
	NSDate* _effectiveAllDayStartDate;
	NSDate* _effectiveAllDayLastValidDate;
	NSDate* _effectiveAllDayEndDate;
	BOOL _effectiveAllDay;
}
@property(assign, nonatomic, getter=isAllDay) BOOL allDay;
+(void)initialize;
-(id)init;
-(void)dealloc;
-(void)setTimeZoneRelativeStartDate:(id)date absoluteStartDate:(id)date2;
-(void)setTimeZoneRelativeEndDate:(id)date;
-(void)setStartDate:(id)date withTimeZone:(id)timeZone;
-(void)setEndDate:(id)date withTimeZone:(id)timeZone;
-(void)_resetEffectiveAllDayState:(BOOL)state;
-(void)_updateEffectiveAllDayTimes;
-(id)_localDateForDate:(id)date inTimeZone:(id)timeZone;
-(BOOL)isDateWithinEffectiveAllDayRange:(id)range;
-(BOOL)isEffectiveAllDay;
-(id)constructLabelString;
-(void)updateTextIfNecessary;
-(void)update;
@end

