/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"


@interface SBDeviceLockPasscodeEntryAlert : SBAlert {
}
+(id)sharedInstance;
-(void)deactivate;
-(int)statusBarStyle;
-(id)alertDisplayViewWithSize:(CGSize)size;
@end

