/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBDimmingWindow : XXUnknownSuperclass {
}
+(CGRect)constrainFrameToScreen:(CGRect)screen;
-(BOOL)_disableGroupOpacity;
-(id)initWithContentRect:(CGRect)contentRect;
-(id)initWithDimmingImage:(id)dimmingImage;
@end

