/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

@interface SBDisplayStack : XXUnknownSuperclass {
	NSMutableArray* _displayStack;
	/*function-pointer*/ void* _pushCallback;
	/*function-pointer*/ void* _popCallback;
}
-(id)init;
-(void)dealloc;
-(void)setPushCallBack:(/*function-pointer*/ void*)back;
-(void)setPopCallBack:(/*function-pointer*/ void*)back;
-(BOOL)isEmpty;
-(void)pushDisplay:(id)display;
-(id)pop;
-(id)popDisplay:(id)display;
-(id)displays;
-(BOOL)containsDisplay:(id)display;
-(id)topDisplay;
-(id)topApplication;
-(id)topAlert;
-(id)description;
@end

