/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconView.h"

@class SBDownloadingProgressBar, SBDownloadingIcon;

@interface SBDownloadingIconView : SBIconView {
	SBDownloadingProgressBar* _progressView;
}
@property(readonly, retain) SBDownloadingIcon* downloadingIcon;
-(id)initWithDefaultSize;
-(void)dealloc;
-(void)setDownloadingIcon:(id)icon;
-(void)setIcon:(id)icon;
-(void)setDisplayedIconImage:(id)image;
-(void)_updateProgressBar;
-(void)setGhostly:(BOOL)ghostly requester:(int)requester;
-(void)iconAccessoriesDidUpdate:(id)iconAccessories;
@end

