/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SSDownloadQueueObserver.h"

@class NSMutableSet, NSMutableArray, SSDownloadQueue;

@interface SBDownloadController : XXUnknownSuperclass <SSDownloadQueueObserver> {
	SSDownloadQueue* _downloadQueue;
	NSMutableSet* _pendingDownloadRemovals;
	NSMutableSet* _pendingDownloadIconsToSwapForApplicationIcons;
	NSMutableArray* _downloads;
	unsigned _downloadLoadCount;
}
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)_finishDownload:(id)download;
-(void)_downloadsEnded;
-(void)_delayedDownloadQueueChange;
-(void)downloadQueue:(id)queue changedWithRemovals:(id)removals;
-(void)_processDownloadQueueChangedWithPendingRemovals;
-(void)downloadQueue:(id)queue downloadStatusChangedAtIndex:(int)index;
-(void)downloadQueueNetworkUsageChanged:(id)changed;
-(void)_showDownloadQueueError;
-(void)downloadQueueError:(id)error;
-(BOOL)checkQueue;
-(id)currentDownloads;
-(void)cancelDownload:(id)download;
-(BOOL)moveDownloadToFrontOfQueue:(id)queue;
-(BOOL)bundledIdentifierIsBeingDownloaded:(id)downloaded;
@end

