/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIView;

@interface SBEmergencyCallView : XXUnknownSuperclass {
	UIView* _topBar;
}
-(id)initWithFrame:(CGRect)frame topBarFrame:(CGRect)frame2 bottomBarFrame:(CGRect)frame3;
-(id)topBar;
-(void)setTopBar:(id)bar;
-(void)dealloc;
@end

