/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBNewsstandApplication.h"


@interface SBFakeNewsstandApplication : SBNewsstandApplication {
}
+(id)fakeApplication;
-(id)init;
-(BOOL)isFakeApp;
@end

