/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBGestureRecognizer.h"


@interface SBFluidSlideGestureRecognizer : SBGestureRecognizer {
	int m_degreeOfFreedom;
	unsigned m_minTouches;
	BOOL m_blocksIconController;
	float _animationDistance;
	float _commitDistance;
	float _accelerationThreshold;
	float _accelerationPower;
	int _requiredDirectionality;
	float _defaultHandSize;
	float _handSizeCompensationPower;
	float _incrementalMotion;
	float _smoothedIncrementalMotion;
	float _cumulativeMotion;
	float _cumulativeMotionEnvelope;
	float _cumulativeMotionSkipped;
	BOOL _hasSignificantMotion;
	CGPoint _movementVelocityInPointsPerSecond;
	CGPoint _centroidPoint;
}
@property(readonly, assign, nonatomic) int degreeOfFreedom;
@property(assign, nonatomic) unsigned minTouches;
@property(assign, nonatomic) float animationDistance;
@property(assign, nonatomic) float accelerationThreshold;
@property(assign, nonatomic) float accelerationPower;
@property(assign, nonatomic) int requiredDirectionality;
@property(readonly, assign, nonatomic) CGPoint movementVelocityInPointsPerSecond;
@property(readonly, assign, nonatomic) CGPoint centroidPoint;
@property(readonly, assign, nonatomic) float incrementalMotion;
@property(readonly, assign, nonatomic) float cumulativeMotion;
@property(readonly, assign, nonatomic) float skippedCumulativePercentage;
@property(readonly, assign, nonatomic) float cumulativePercentage;
-(id)init;
-(void)reset;
-(void)skipCumulativeMotion;
-(float)computeNonlinearSpeedGain:(float)gain;
-(float)computeHandSizeCompensationGain:(float)gain;
-(void)computeGestureMotion:(SBGestureContextRef)motion;
-(float)computeIncrementalGestureMotion:(SBGestureContextRef)motion;
-(void)computeHasSignificantMotionIfNeeded:(SBGestureContextRef)needed;
-(void)computeCentroidPoint:(SBGestureContextRef)point;
-(float)projectMotionForInterval:(double)interval;
-(int)completionTypeProjectingMomentumForInterval:(double)interval;
-(void)updateForBeganOrMovedTouches:(SBGestureContextRef)beganOrMovedTouches;
-(void)updateForEndedOrCancelledTouches:(SBGestureContextRef)endedOrCancelledTouches;
-(void)updateActiveTouches:(SBGestureContextRef)touches;
-(void)touchesBegan:(SBGestureContextRef)began;
-(void)touchesMoved:(SBGestureContextRef)moved;
-(void)touchesEnded:(SBGestureContextRef)ended;
-(void)touchesCancelled:(SBGestureContextRef)cancelled;
@end

