/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UITextInteractionAssistant;

@interface SBFolderTextField : XXUnknownSuperclass {
}
@property(readonly, assign, nonatomic) UITextInteractionAssistant* interactionAssistant;
-(id)initWithFrame:(CGRect)frame;
-(CGRect)textRectForBounds:(CGRect)bounds;
-(CGRect)editingRectForBounds:(CGRect)bounds;
@end

