/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBFolderIcon, NSMutableDictionary, NSMutableSet, NSString, NSMutableArray;

@interface SBFolder : XXUnknownSuperclass {
	NSString* _displayName;
	NSString* _defaultDisplayName;
	NSMutableArray* _lists;
	BOOL _open;
	SBFolderIcon* _icon;
	BOOL _cancelable;
	NSMutableSet* _addedIcons;
	NSMutableSet* _removedIcons;
	NSMutableDictionary* _coalesceChangesRequests;
}
@property(retain, nonatomic) NSString* displayName;
@property(assign, nonatomic) BOOL isOpen;
@property(assign, nonatomic) SBFolderIcon* icon;
@property(assign, nonatomic, getter=isCancelable) BOOL cancelable;
+(int)maxListCount;
-(Class)listModelClass;
-(Class)listViewClass;
-(Class)folderViewClass;
-(Class)folderSlidingViewClass;
-(id)init;
-(void)dealloc;
-(void)purgeIconImages;
-(id)lists;
-(unsigned)listCount;
-(BOOL)isEmpty;
-(BOOL)isFull;
-(BOOL)isNewsstandFolder;
-(BOOL)compactLists;
-(void)compactIconsAndLists;
-(id)addEmptyList;
-(void)removeEmptyList:(id)list;
-(BOOL)isIconStateDirty;
-(void)markIconStateClean;
-(id)listAtIndex:(unsigned)index;
-(unsigned)indexOfList:(id)list;
-(void)purgeLists;
-(id)placeIcon:(id)icon atIndexPath:(id*)indexPath;
-(id)insertIcon:(id)icon atIndexPath:(id*)indexPath;
-(void)removeIconAtIndexPath:(id)indexPath;
-(id)addIcon:(id)icon;
-(BOOL)canAddIcon;
-(id)performCascadingIconInsertion:(id)insertion listIndex:(unsigned)index iconIndex:(unsigned)index3 addPageIfNecessary:(BOOL)necessary;
-(id)indexPathForFirstFreeSlotAvoidingFirstList:(BOOL)firstFreeSlotAvoidingFirstList;
-(id)iconsOfClass:(Class)aClass;
-(id)allIcons;
-(id)leafIcons;
-(id)folderIcons;
-(id)visibleIcons;
-(id)listContainingIcon:(id)icon;
-(id)listContainingLeafIconWithIdentifier:(id)identifier;
-(id)indexPathForIcon:(id)icon;
-(id)indexPathForIconWithIdentifier:(id)identifier;
-(id)iconAtIndexPath:(id)indexPath;
-(id)folderContainingIndexPath:(id)path relativeIndexPath:(id*)path2;
-(id)folderContainingIcon:(id)icon relativeIndexPath:(id*)path;
-(id)indexPathForEntity:(id)entity;
-(BOOL)_isCoalescingContentChanges;
-(void)noteIconAdded:(id)added;
-(void)noteIconRemoved:(id)removed;
-(void)noteIcon:(id)icon replacedIcon:(id)icon2;
-(void)startCoalescingContentChangesWithRequestID:(id)requestID;
-(void)stopCoalescingContentChangesForRequestID:(id)requestID;
-(void)stopCoalescingContentChangesForRequestID:(id)requestID forceReload:(BOOL)reload;
-(void)_setDisplayNameFromRepresentation:(id)representation;
-(BOOL)resetWithRepresentation:(id)representation leafIdentifiersAdded:(id)added;
-(id)folderType;
-(id)representation;
-(BOOL)matchesRepresentation:(id)representation;
@end

