/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBFolderScrollOffset : XXUnknownSuperclass {
	CGPoint _scrollOffset;
	unsigned _identifier;
	int _orientation;
}
@property(assign) CGPoint scrollOffset;
@property(assign) int orientation;
@property(assign) unsigned identifier;
@end

