/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UITextFieldDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBFolderIconListView, SBFolder, UIImageView, UILabel, UIView, SBFolderTextField;

@interface SBFolderView : XXUnknownSuperclass <UITextFieldDelegate> {
	SBFolder* _folder;
	UILabel* _label;
	SBFolderTextField* _textField;
	SBFolderIconListView* _iconListView;
	UIView* _backgroundView;
	BOOL _isEditing;
	UIImageView* _shadows[12];
	unsigned _rows;
	XXStruct_9ihRqB _notchInfo;
	int _orientation;
}
-(id)initWithFrame:(CGRect)frame;
-(void)_setupNavigationBar;
-(void)_setupBackgroundView;
-(void)_setupFolderTitleLabel;
-(CGSize)_sizeForCurrentConfiguration;
-(void)prepareToSetOrientation:(int)setOrientation;
-(void)setRows:(unsigned)rows notchInfo:(XXStruct_9ihRqB)info orientation:(int)orientation;
-(void)cleanUpAfterOrientationChange;
-(void)prepareToDropIconView:(id)dropIconView targetFolderBounds:(CGRect*)bounds;
-(void)didDropIconView;
-(unsigned)rows;
-(Class)notchViewClass;
-(CGRect)rectForNotchLinen;
-(void)_createInitialIconViews;
-(void)setIconListView:(id)view;
-(void)noteHasGrabbedIcon:(id)icon;
-(void)noteGrabbedIconLocation:(CGPoint)location;
-(BOOL)isScrolling;
-(id)scrollOffset;
-(void)setScrollOffset:(id)offset;
-(void)_placeIconListView;
-(id)iconListView;
-(void)dealloc;
-(void)setFolder:(id)folder;
-(float)_labelHorizontalInset;
-(float)_labelVerticalInset;
-(void)setFolderName:(id)name;
-(void)_placeLabelAndTextField;
-(void)_placeBackgroundView;
-(void)_placeBars;
-(BOOL)canEditTitle;
-(void)setIsEditing:(BOOL)editing animated:(BOOL)animated;
-(void)enableShiftForFolderTextFieldAfterBeginEditing;
-(void)textFieldDidBeginEditing:(id)textField;
-(void)textFieldDidEndEditing:(id)textField;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)textFieldShouldClear:(id)textField;
-(NSRange)textField:(id)field willChangeSelectionFromCharacterRange:(NSRange)characterRange toCharacterRange:(NSRange)characterRange3;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)setBackgroundAlpha:(float)alpha;
-(id)editTitleField;
-(id)_shadowForPosition:(int)position;
-(void)_placeShadow:(int)shadow;
-(void)_placeShadows;
@end

