/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIcon.h"
#import "SpringBoard-Structs.h"

@class SBFolder;

@interface SBFolderIcon : SBIcon {
	SBFolder* _folder;
	float _progress;
}
@property(readonly, assign) float progress;
-(id)initWithFolder:(id)folder;
-(void)dealloc;
-(id)generateIconImage:(int)image;
-(id)getGenericIconImage:(int)image;
-(id)croppedImageForIcon:(id)icon;
-(id)iconOverlayImageForLocation:(int)location;
-(id)displayName;
-(id)representation;
-(BOOL)matchesRepresentation:(id)representation;
-(id)folder;
-(id)description;
-(void)launch;
-(void)updateLabel;
-(void)_updateBadgeValue;
-(void)_updateProgressBar;
-(void)noteContainedIconsAdded:(id)added removed:(id)removed;
-(void)noteContainedIcon:(id)icon replacedIcon:(id)icon2;
-(void)noteContainedIconBadgeChanged:(id)changed;
-(id)updateGridImageIcon:(id)icon inGrid:(id)grid withImage:(id)image skipping:(BOOL)skipping;
-(void)noteContainedIconImageChanged:(id)changed;
-(void)noteContainedIconDownloadingStateChanged:(id)changed;
-(CGSize)_sizeOfMiniIconGridWithRows:(unsigned)rows;
-(CGRect)_rectForMiniIconImage:(id)miniIconImage atIndex:(unsigned)index;
-(CGRect)_rectForMiniIconAtIndex:(unsigned)index;
-(id)_miniIconGridWithSkipping:(BOOL)skipping;
-(unsigned)_maxIcons;
-(float)_miniIconSize;
-(float)_miniIconGap;
-(unsigned)_gridRows;
-(unsigned)_gridColumns;
-(unsigned)_firstSkippedIconIndex;
-(unsigned)_numberOfExcessIcons;
-(unsigned)_skippingIconThreshold;
-(id)miniImageForIcon:(id)icon;
-(BOOL)shouldSkipIcons;
-(id)gridImageWithSkipping:(BOOL)skipping;
@end

