/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class CPLRUDictionary;

@interface SBGestureViewVendor : XXUnknownSuperclass {
	CPLRUDictionary* m_cache;
}
+(id)sharedInstance;
-(id)viewForApp:(id)app gestureType:(int)type includeStatusBar:(BOOL)bar;
-(id)viewForApp:(id)app gestureType:(int)type includeStatusBar:(BOOL)bar decodeImage:(BOOL)image;
-(void)clearCacheForApp:(id)app reason:(id)reason;
-(void)clearCacheForReason:(id)reason;
-(id)init;
-(void)dealloc;
-(void)maskViewIfNeeded:(id)needed gestureType:(int)type viewType:(int)type3 contextHostViewRequester:(id)requester app:(id)app;
@end

