/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBGuideDomainLabel : XXUnknownSuperclass {
}
-(void)drawRect:(CGRect)rect;
@end

