/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class NSString, UIImageView, UIImage, UILabel;

@interface SBHUDView : XXUnknownSuperclass {
	int _level;
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
	UIImageView* _imageView;
	BOOL _showsProgress;
	float _progress;
}
@property(assign, nonatomic) int level;
@property(assign, nonatomic) BOOL showsProgress;
@property(assign, nonatomic) float progress;
@property(retain, nonatomic) UIImage* image;
@property(retain, nonatomic) NSString* subtitle;
@property(retain, nonatomic) NSString* title;
+(int)numberOfProgressIndicatorSteps;
+(float)progressIndicatorStep;
-(id)initWithHUDViewLevel:(int)hudviewLevel;
-(void)dealloc;
-(BOOL)displaysLabel;
-(void)layoutSubviews;
-(void)drawRect:(CGRect)rect;
@end

