/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBIconScrollView : XXUnknownSuperclass {
}
-(BOOL)cancelTouchTracking;
-(BOOL)_scrollsToMakeFirstResponderVisible;
-(void)setContentOffset:(CGPoint)offset;
@end

