/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class NSString, SBIconLabelImage;

@interface SBIconLabel : XXUnknownSuperclass {
	SBIconLabelImage* _labelImage;
	NSString* _label;
	unsigned _drawMoreLegibly : 1;
	unsigned _inDock : 1;
	unsigned _ellipsizesText : 1;
	unsigned _onWallpaper : 1;
}
-(id)initWithSize:(CGSize)size text:(id)text inDock:(BOOL)dock onWallpaper:(BOOL)wallpaper ellipsizes:(BOOL)ellipsizes;
-(void)dealloc;
-(id)description;
-(void)setText:(id)text;
-(void)setInDock:(BOOL)dock;
-(void)setDisplaysOnWallpaper:(BOOL)wallpaper;
-(void)setEllipsizesText:(BOOL)text;
-(void)setBounds:(CGRect)bounds;
-(void)setFrame:(CGRect)frame;
-(id)_textFont;
-(float)heightOfCurrentString;
-(id)_textColor;
-(id)_textShadowColor;
-(CGSize)_textShadowOffset;
-(void)_updateImage;
-(CGImageRef)buildLabelImage;
@end

