/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, SBIcon, NSMutableArray, UIView, SBIconListModel;

@interface SBIconListView : XXUnknownSuperclass {
	SBIconListModel* _model;
	int _orientation;
	SBIcon* _bouncedIcon;
	NSMutableArray* _removedIcons;
	NSMutableArray* _iconContainerMatrix;
	unsigned _scattered : 1;
	unsigned _needsLayout : 1;
	unsigned _rotating : 1;
	unsigned _onWallpaper : 1;
	UIView* _fadeView;
	BOOL _iconsAreElsewhere;
	BOOL _recyclesIconViewsWhenNotShowing;
	NSMutableSet* _notShownIconViews;
	BOOL _showingCloseBoxes;
}
+(unsigned)iconRowsForInterfaceOrientation:(int)interfaceOrientation;
+(unsigned)maxVisibleIconRowsInterfaceOrientation:(int)orientation;
+(unsigned)iconColumnsForInterfaceOrientation:(int)interfaceOrientation;
+(unsigned)maxIcons;
-(Class)modelClass;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setModel:(id)model;
-(id)model;
-(unsigned)iconRowsForCurrentOrientation;
-(unsigned)iconColumnsForCurrentOrientation;
-(unsigned)iconsInRowForSpacingCalculation;
-(void)setOrientation:(int)orientation;
-(void)setDisplaysOnWallpaper:(BOOL)wallpaper;
-(unsigned)indexForX:(unsigned)x Y:(unsigned)y forOrientation:(int)orientation;
-(void)getX:(unsigned*)x Y:(unsigned*)y forIndex:(unsigned)index forOrientation:(int)orientation;
-(unsigned)rowForIcon:(id)icon;
-(BOOL)compactIcons:(BOOL)icons;
-(id)icons;
-(id)visibleIcons;
-(BOOL)isEmpty;
-(BOOL)isFull;
-(unsigned)firstFreeSlotIndex;
-(unsigned)firstFreeSlotIndexForType:(int)type;
-(unsigned)firstFreeSlotOrLastSlotIndex;
-(unsigned)firstFreeSlotOrLastSlotIndexForType:(int)type;
-(void)showIconAnimationDidStop:(id)showIconAnimation didFinish:(id)finish iconView:(id)view;
-(void)_popIconView:(id)view;
-(void)_noteNewIconInModel:(id)model;
-(id)placeIcon:(id)icon atIndex:(unsigned)index moveNow:(BOOL)now pop:(BOOL)pop;
-(id)insertIcon:(id)icon atIndex:(unsigned)index moveNow:(BOOL)now pop:(BOOL)pop;
-(id)insertIcon:(id)icon atIndex:(unsigned)index moveNow:(BOOL)now;
-(id)removedIcons;
-(void)removeIconAtIndex:(unsigned)index;
-(void)removeIcon:(id)icon;
-(BOOL)isScattered;
-(void)setAlphaForAllIcons:(float)allIcons;
-(void)scatterAnimationDidStop;
-(void)scatterWithDuration:(double)duration startTime:(double)time;
-(void)unscatterAnimationDidStop;
-(void)unscatterWithDuration:(double)duration startTime:(double)time;
-(void)removeAllIconAnimations;
-(CGSize)defaultIconSize;
-(CGPoint)originForIconAtIndex:(int)index;
-(CGPoint)originForIcon:(id)icon;
-(void)setFrame:(CGRect)frame;
-(void)setIconsAreElsewhere:(BOOL)elsewhere;
-(BOOL)iconsAreElsewhere;
-(void)setRecyclesIconViewsWhenNotShowing:(BOOL)showing;
-(BOOL)recyclesIconViewsWhenNotShowing;
-(void)setIconsNeedLayout;
-(void)layoutIconsNow;
-(CATransform3D)_transformForIconAtIndex:(unsigned)index inOrientation:(int)orientation;
-(float)layoutIconsIfNeeded:(float)needed domino:(BOOL)domino;
-(id)iconAtPoint:(CGPoint)point index:(unsigned*)index;
-(id)iconAtPoint:(CGPoint)point index:(unsigned*)index proposedOrder:(int*)order grabbedIcon:(id)icon;
-(void)showIconImagesFromColumn:(int)column toColumn:(int)column2 totalColumns:(int)columns visibleIconsJitter:(BOOL)jitter;
-(void)stopJittering;
-(void)startJittering;
-(void)showCloseBoxes;
-(void)hideCloseBoxes;
-(void)makeIconsPerformSelector:(SEL)selector;
-(void)makeIconViewsPerformSelector:(SEL)selector;
-(void)makeIconsPerformBlock:(id)block;
-(void)makeIconViewsPerformBlock:(id)block;
-(BOOL)isDock;
-(void)setBouncedIcon:(id)icon;
-(id)bouncedIcon;
-(float)topIconInset;
-(float)bottomIconInset;
-(float)sideIconInset;
-(float)horizontalBumpForColumn:(unsigned)column;
-(float)horizontalIconPadding;
-(float)verticalIconPadding;
-(CGPoint)originForIconAtX:(unsigned)x Y:(unsigned)y;
-(unsigned)columnAtPoint:(CGPoint)point;
-(unsigned)rowAtPoint:(CGPoint)point;
-(unsigned)_preRotationFirstVisibleRow;
-(unsigned)_postRotationFirstVisibleRow;
-(unsigned)_rotationReferenceRow;
-(id)rotationIconContainers;
-(Class)iconRotationContainerClass;
-(void)prepareToRotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)performRotationWithDuration:(double)duration;
-(void)cleanupAfterRotation;
@end

