/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, SBFolder;

@interface SBIconListModel : XXUnknownSuperclass {
	NSMutableArray* _icons;
	BOOL _iconStateIsDirty;
	SBFolder* _folder;
}
+(Class)viewClass;
+(unsigned)maxIcons;
-(id)initWithFolder:(id)folder;
-(void)dealloc;
-(id)folder;
-(id)icons;
-(id)iconAtIndex:(unsigned)index;
-(unsigned)indexForIcon:(id)icon;
-(unsigned)indexForLeafIconWithIdentifier:(id)identifier;
-(BOOL)containsIcon:(id)icon;
-(BOOL)containsLeafIconWithIdentifier:(id)identifier;
-(BOOL)allowsAddingIcon:(id)icon;
-(void)notifyAdded:(id)added;
-(BOOL)addIcon:(id)icon;
-(BOOL)addIcon:(id)icon asDirty:(BOOL)dirty;
-(id)placeIcon:(id)icon atIndex:(unsigned*)index;
-(id)placeIcon:(id)icon atIndex:(unsigned*)index notify:(BOOL)notify;
-(id)insertIcon:(id)icon atIndex:(unsigned*)index;
-(void)removeIconAtIndex:(unsigned)index;
-(void)removeIcon:(id)icon;
-(unsigned)firstFreeSlotIndex;
-(unsigned)firstFreeSlotIndexForType:(int)type;
-(BOOL)isEmpty;
-(BOOL)isFull;
-(BOOL)needsCompacting;
-(void)compactIcons;
-(id)iconsOfClass:(Class)aClass;
-(id)indexPathForEntity:(id)entity;
-(id)indexPathForFirstFreeSlot;
-(BOOL)isIconStateDirty;
-(void)markIconStateClean;
-(BOOL)resetWithRepresentation:(id)representation leafIdentifiersAdded:(id)added;
-(id)representation;
-(BOOL)matchesRepresentation:(id)representation;
-(id)description;
@end

