/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIcon.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSHashTable, UIImage;
@protocol SBIconDelegate;

@interface SBIcon : XXUnknownSuperclass {
	NSHashTable* _observers;
	id _badgeNumberOrString;
	unsigned _isRevealable : 1;
	unsigned _uninstalled : 1;
	UIImage* _cachedIconImages[12];
	id<SBIconDelegate> _delegate;
}
@property(assign, nonatomic) id<SBIconDelegate> delegate;
@property(readonly, assign, nonatomic) BOOL shouldWarmUp;
-(void)addObserver:(id)observer;
-(void)removeObserver:(id)observer;
-(BOOL)hasObserver:(id)observer;
-(int)iconFormatForLocation:(int)location;
-(id)iconOverlayImageForLocation:(int)location;
-(id)init;
-(void)dealloc;
-(id)representation;
-(BOOL)matchesRepresentation:(id)representation;
-(void)localeChanged;
-(void)setIsRevealable:(BOOL)revealable;
-(BOOL)isRevealable;
-(id)displayName;
-(BOOL)canEllipsizeLabel;
-(int)localizedCompareDisplayNames:(id)names;
-(BOOL)matchesEntity:(id)entity;
-(id)tags;
-(BOOL)launchEnabled;
-(id)generateIconImage:(int)image;
-(BOOL)shouldCacheImageForFormat:(int)format;
-(id)getStandardIconImageForLocation:(int)location;
-(id)getIconImage:(int)image;
-(id)getGenericIconImage:(int)image;
-(void)purgeCachedImages;
-(void)reloadIconImage;
-(void)reloadIconImagePurgingImageCache:(BOOL)cache;
-(int)badgeValue;
-(id)badgeNumberOrString;
-(void)noteBadgeDidChange;
-(void)setBadge:(id)badge;
-(id)automationID;
-(void)launch;
-(void)launchFromViewSwitcher;
-(BOOL)allowsUninstall;
-(void)completeUninstall;
-(void)setUninstalled;
-(BOOL)isUninstalled;
-(id)uninstallAlertTitle;
-(id)uninstallAlertTitleForAppWithDocumentsInCloud;
-(id)uninstallAlertTitleForAppWithDocumentUpdatesPending;
-(id)uninstallAlertBody;
-(id)uninstallAlertBodyForAppWithDocumentsInCloud;
-(id)uninstallAlertBodyForAppWithDocumentUpdatesPending;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertCancelTitle;
-(id)folderTitleOptions;
-(id)folderFallbackTitle;
@end

@interface SBIcon (SBApplicationIcon)
-(BOOL)isApplicationIcon;
-(id)application;
@end

@interface SBIcon (SBBookmarkIcon)
-(BOOL)isBookmarkIcon;
@end

@interface SBIcon (SBDownloadingIcon)
-(BOOL)isDownloadingIcon;
-(id)download;
@end

@interface SBIcon (SBUserInstalledApplicationIcon)
-(BOOL)isUserInstalledApplicationIcon;
@end

@interface SBIcon (SBWebApplicationIcon)
-(BOOL)isWebApplicationIcon;
@end

@interface SBIcon (SBFolderIcon)
-(BOOL)isFolderIcon;
-(id)folder;
-(id)enclosingFolder;
@end

@interface SBIcon (SBLeafIcon)
-(BOOL)isLeafIcon;
-(id)leafIdentifier;
-(id)webClip;
-(id)applicationBundleID;
@end

@interface SBIcon (SBPrintStatusIcon)
-(BOOL)isPrintStatusIcon;
@end

@interface SBIcon (SBDestinationHole)
-(BOOL)isDestinationHole;
@end

@interface SBIcon (SBNullIcon)
-(BOOL)isNullIcon;
@end

@interface SBIcon (Internal)
-(void)_notifyImageDidUpdate;
-(void)_notifyAccessoriesDidUpdate;
-(void)_notifyLaunchEnabledDidChange;
@end

@interface SBIcon (SBNewsstandApplicationIcon)
-(BOOL)isNewsstandApplicationIcon;
-(BOOL)iconAppearsInNewsstand;
@end

@interface SBIcon (SBNewsstandIcon)
-(BOOL)isNewsstandIcon;
@end

