/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

@interface SBIconBadgeFactory : XXUnknownSuperclass {
	NSMutableDictionary* _badgesForText;
}
+(id)sharedInstance;
+(float)badgeLabelVerticalOffset;
-(id)init;
-(void)dealloc;
-(id)badgeTextForIcon:(id)icon;
-(id)checkoutBadgeImageForText:(id)text;
-(void)checkinBadgeImage:(id)image;
@end

