/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBDisplay, NSString;

@interface SBLaunchAlertItem : XXUnknownSuperclass {
	SBDisplay* _associatedDisplay;
	int _type;
	NSString* _bundleID;
	BOOL _isDataAlert;
	BOOL _usesCellNetwork;
}
-(id)initWithLaunchAlertType:(int)launchAlertType dataAlert:(BOOL)alert usesCellNetwork:(BOOL)network bundleID:(id)anId;
-(void)dealloc;
-(void)setAssociatedWithDisplay:(id)display;
-(void)_displayDeactivated:(id)deactivated;
-(BOOL)dismissOnLock;
-(id)_customAirplaneModeAlertPrompt;
-(id)alertSheet;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
@end

