/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIcon.h"


@interface SBLeafIcon : SBIcon {
}
-(id)representation;
-(BOOL)matchesRepresentation:(id)representation;
-(id)description;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
@end

