/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class NSMutableArray;

@interface SBLinenView : XXUnknownSuperclass {
	int _type;
	NSMutableArray* _strips;
}
@property(assign, nonatomic) int type;
+(void)setupCache;
+(void)removeCacheFiles;
+(id)_folderSwitcherLinenPath;
+(id)_allFolderSwitcherLinenPaths:(BOOL)paths;
+(CGRect)_scaledRectForIndex:(unsigned)index ofImage:(id)image;
+(void)_generateLinenStripsIfNeeded;
+(float)naturalWidth;
+(id)squareImageForBounds:(CGRect)bounds;
+(id)_imageForIndex:(unsigned)index;
+(id)_imageViewForIndex:(unsigned)index;
+(float)_vOffsetOfTopForType:(int)type;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setFrame:(CGRect)frame;
-(void)_layoutForBounds:(CGRect)bounds;
-(void)layoutSubviews;
-(float)_vOffsetOfTop;
@end

