/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBDismissOnlyAlertItem, NSString;

@interface SBLockdownManager : XXUnknownSuperclass {
	int _state;
	BOOL _settingUpActivationState;
	BOOL _isBricked;
	BOOL _isInternalInstall;
	BOOL _isDeveloperDevice;
	BOOL _hasShownMismatchedSIM;
	SBDismissOnlyAlertItem* _activatingAlertItem;
	NSString* _unqiueDeviceIdentifier;
}
+(id)sharedInstance;
-(id)init;
-(BOOL)_hasEverRegistered;
-(void)_setHasEverRegistered:(BOOL)registered;
-(BOOL)_isRegisteredToNetwork;
-(void)_setCurrentAlertItem:(id)item;
-(BOOL)_shouldShowTelephonyAlerts;
-(void)_postAlertsIfNeeded;
-(void)_resetActivationState;
-(void)_activationFailed;
-(void)_developerDeviceStateChanged;
-(void)_serviceAvailabilityChanged:(id)changed;
-(void)_setupActivationState;
-(BOOL)brickedDevice;
-(BOOL)isInternalInstall;
-(BOOL)isDeveloperDevice;
-(int)lockdownState;
-(id)uniqueDeviceIdentifier;
-(void)dealloc;
-(id)valueForDomain:(id)domain key:(id)key;
@end

