/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBLowPowerAlertItem : XXUnknownSuperclass {
	unsigned _talkLevel;
}
+(id)systemVersionDescription;
+(void)saveLowBatteryLogWithCapacity:(int)capacity voltage:(int)voltage;
+(void)initialize;
+(unsigned)_thresholdForLevel:(unsigned)level;
+(BOOL)_shouldIgnoreChangeToBatteryLevel:(unsigned)batteryLevel;
+(void)setBatteryLevel:(unsigned)level;
-(id)init;
-(id)initWithLevel:(unsigned)level;
-(void)willPresentAlertView:(id)view;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(BOOL)shouldShowInLockScreen;
-(BOOL)shouldShowInEmergencyCall;
-(BOOL)undimsScreen;
@end

