/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBLockScreenAudioRoutesAlertItem : XXUnknownSuperclass {
}
-(Class)alertSheetClass;
-(id)alertSheet;
-(BOOL)allowMenuButtonDismissal;
-(void)willRelockForButtonPress:(BOOL)buttonPress;
-(BOOL)shouldShowInLockScreen;
-(BOOL)togglesMediaControls;
-(BOOL)allowAutoUnlock;
-(void)performUnlockAction;
-(void)audioRoutingPicker:(id)picker didSelectRouteAtIndex:(int)index;
@end

