/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconLabelProperties.h"
#import "SpringBoard-Structs.h"

@class NSString;

@interface SBMutableIconLabelProperties : SBIconLabelProperties {
}
@property(retain, nonatomic) NSString* text;
@property(assign, nonatomic) Class labelClass;
@property(assign, nonatomic) BOOL ellipsize;
@property(assign, nonatomic) BOOL appearsInDock;
@property(assign, nonatomic) BOOL appearsOnWallpaper;
@property(assign, nonatomic) CGSize size;
@end

