/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconListModel.h"


@interface SBNewsstandIconListModel : SBIconListModel {
}
+(Class)viewClass;
-(BOOL)allowsAddingIcon:(id)icon;
-(unsigned)firstFreeSlotIndexForType:(int)type;
@end

