/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBPhoneAlertItem.h"


@interface SBNetworkReselectionAlertItem : SBPhoneAlertItem {
}
-(id)init;
-(void)_showPrefs;
-(id)lockLabel;
-(id)shortLockLabel;
-(void)performUnlockAction;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
@end

