/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconLabel.h"
#import "SpringBoard-Structs.h"


@interface SBNewsstandIconLabel : SBIconLabel {
}
-(id)_textColor;
-(id)_textShadowColor;
-(CGSize)_textShadowOffset;
-(id)_textFont;
@end

