/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFolderIconView.h"


@interface SBNewsstandIconView : SBFolderIconView {
}
-(id)_folderBackgroundImage;
-(id)_folderForegroundImage;
-(void)setIconScrollPosition:(int)position animated:(BOOL)animated;
-(void)_positionMiniGrid;
-(void)positionIconImageView;
-(void)placeIconOverlayView;
@end

