/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"


@interface SBNetworkReselectionAlert : SBAlert {
}
+(void)registerForAlerts;
+(void)test;
+(void)_serviceAvailabilityChanged:(id)changed;
@end

