/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView;

@interface SBNewsstandShelfTableView : XXUnknownSuperclass {
	UIView* _backView;
}
@property(assign, nonatomic) UIView* shelfFrameView;
-(void)didAddSubview:(id)subview;
-(void)willRemoveSubview:(id)subview;
-(void)reloadData;
@end

