/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIImageView;

@interface SBNewsstandShelfView : XXUnknownSuperclass {
	UIImageView* _body;
	UIImageView* _leftEdge;
	UIImageView* _rightEdge;
	UIImageView* _shadowLeft;
	UIImageView* _shadowMiddle;
	UIImageView* _shadowRight;
	int _orientation;
	unsigned _shelfIndex;
	UILabel* _label;
}
+(float)shelfHeight;
+(float)shelfEdgeHeight;
+(float)shelfItemBaselineOffset;
+(id)reuseIdentifier;
+(id)shelf;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(void)dealloc;
-(unsigned)shelfIndex;
-(void)configureForOrientation:(int)orientation shelfIndex:(unsigned)index;
@end

