/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBNewsstand : XXUnknownSuperclass {
}
+(void)initialize;
+(void)_buildCacheDirectory;
+(id)cachePath;
+(void)setupCache;
+(void)removeCacheFiles;
+(void)removeLocalizedCacheFiles;
+(void)openNewsstandAppStore;
+(void)_loadDefaults;
+(void)_updateStoreAvailability;
+(void)_checkStoreSupport;
+(void)noteCapabilitiesDidChange;
+(void)reloadDefaults;
+(void)_availableStoreItemKindsDidChange:(id)_availableStoreItemKinds;
+(void)_iconVisibilityDidChange:(id)_iconVisibility;
+(BOOL)newsstandEnabled;
+(BOOL)newsstandStoreIsAvailable;
+(BOOL)_newsstandStoreIsRestricted;
+(BOOL)_newsstandStoreIsSupported;
+(BOOL)disableIconSkew;
+(BOOL)alwaysShowIconLabels;
+(BOOL)addManyIcons;
+(id)bundleIDToReplicate;
+(BOOL)debugRotation;
+(BOOL)addFakeApps;
@end

