/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBFolder.h"


@interface SBNewsstandFolder : SBFolder {
}
+(int)maxListCount;
-(id)init;
-(id)icon;
-(void)setIsOpen:(BOOL)open;
-(Class)listModelClass;
-(Class)listViewClass;
-(Class)folderViewClass;
-(BOOL)isNewsstandFolder;
-(id)folderType;
-(BOOL)canAddIcon;
-(void)_setDisplayNameFromRepresentation:(id)representation;
@end

