/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class SBNewsstandShelfHeaderView, SBNewsstandTilingImageView;

@interface SBNewsstandShelfFrameView : XXUnknownSuperclass {
	CGSize _borderSize;
	SBNewsstandShelfHeaderView* _headerView;
	SBNewsstandTilingImageView* _leftBorder;
	SBNewsstandTilingImageView* _rightBorder;
	int _orientation;
}
+(void)setupCache;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)showHeaderView;
-(void)setFrame:(CGRect)frame;
-(void)configureForOrientation:(int)orientation;
-(void)layoutSubviews;
@end

