/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconRotationContainer.h"


@interface SBNewsstandIconRotationContainer : SBIconRotationContainer {
}
-(void)setStartIcon:(id)icon endIcon:(id)icon2 inIconList:(id)iconList fromOrientation:(int)orientation toOrientation:(int)orientation5;
-(void)crossfadeWithDuration:(double)duration inIconList:(id)iconList;
@end

