/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBNowPlayingPushButton : XXUnknownSuperclass {
	float _yOffset;
	float _xOffset;
}
+(id)newButtonWithImage:(id)image;
-(void)setYOffset:(float)offset;
-(void)setXOffset:(float)offset;
-(CGRect)hitRect;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
@end

