/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIButton, SBIconLabel, UILabel;

@interface SBNowPlayingBarMediaControlsView : XXUnknownSuperclass {
	UIButton* _prevButton;
	UIButton* _playButton;
	UIButton* _nextButton;
	UIButton* _airPlayButton;
	UILabel* _trackLabel;
	int _toggleType;
	SBIconLabel* _toggleLabel;
	BOOL _isAirPlayVisible;
	BOOL _isPlaying;
	BOOL _isEnabled;
	BOOL _showingToggleLabel;
}
@property(readonly, assign, nonatomic) UIButton* prevButton;
@property(readonly, assign, nonatomic) UIButton* playButton;
@property(readonly, assign, nonatomic) UIButton* nextButton;
@property(readonly, assign, nonatomic) UIButton* airPlayButton;
@property(assign, nonatomic) BOOL airPlayButtonVisible;
@property(assign, nonatomic) BOOL marqueeRunning;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)updateImages:(BOOL)images enabled:(BOOL)enabled;
-(void)layoutSubviews;
-(void)_layoutForiPhone;
-(void)_layoutForiPad;
-(void)setTrackString:(id)string;
-(void)setLabelWidth:(float)width;
-(id)_descriptionLabel;
-(void)_toggleStatus:(id)status;
-(void)_setToggleType:(int)type;
-(id)_toggleLabelText;
-(void)_orientationLockChanged:(id)changed;
-(void)_muteChanged:(id)changed;
@end

