/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UILabel;

@interface SBNoResultsView : XXUnknownSuperclass {
	UILabel* _noResultsLabel;
}
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setShowsText:(BOOL)text;
@end

