/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBSwitcherPopoverWindowControllerDelegate.h"
#import "UIPopoverControllerDelegate.h"
#import "SBIconViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBSwitcherVolumeSlider, MPAudioVideoRoutingActionSheet, UIViewController, MPAudioVideoRoutingPopoverController, SBAirPlayBarView, UIButton, SBApplication, SBNowPlayingBarView, MPAudioDeviceController;

@interface SBNowPlayingBar : XXUnknownSuperclass <SBIconViewDelegate, UIPopoverControllerDelegate, SBSwitcherPopoverWindowControllerDelegate> {
	SBNowPlayingBarView* _barView;
	SBAirPlayBarView* _airPlayView;
	MPAudioVideoRoutingActionSheet* _airPlayActionSheet;
	UIViewController* _airPlayController;
	SBSwitcherVolumeSlider* _volumeSlider;
	UIButton* _airPlayButton;
	SBApplication* _nowPlayingApp;
	int _scanDirection;
	MPAudioDeviceController* _audioDeviceController;
	MPAudioVideoRoutingPopoverController* _audioRoutingPopoverController;
	BOOL _audioRoutingPopoverVisible;
	BOOL _showPopoverWhenRotationComplete;
}
-(id)init;
-(void)dealloc;
-(id)views;
-(int)scanDirection;
-(void)viewAtIndexDidAppear:(int)viewAtIndex;
-(void)viewAtIndexDidDisappear:(int)viewAtIndex;
-(void)viewDidAppear;
-(void)prepareToDisappear;
-(BOOL)shouldScrollCancelInContentForView:(id)view;
-(void)_updateDisplay;
-(void)_toggleButtonHit:(id)hit;
-(void)_playButtonHit:(id)hit;
-(void)_trackButtonUp:(id)up;
-(void)_trackButtonCancel:(id)cancel;
-(void)_trackButtonDown:(id)down;
-(void)_trackButtonDownSeek:(id)seek;
-(void)_updateNowPlayingApp;
-(void)_updateNowPlayingInfo;
-(void)_nowPlayingInfoChanged;
-(void)_updateNowPlayingButtonImages;
-(void)_updateAudioRouteDisplay:(BOOL)display;
-(void)_iapExtendedModeChanged:(id)changed;
-(void)_brightnessSliderChanged:(id)changed;
-(void)_airPlayButtonHit:(id)hit;
-(void)_dismissAirPlayDetail;
-(BOOL)_shouldShowAirPlayButton;
-(void)_showAudioRoutingPopover;
-(BOOL)_isAirPlayOn;
-(void)iconTapped:(id)tapped;
-(BOOL)iconShouldAllowTap:(id)icon;
-(void)iconTouchBegan:(id)began;
-(void)backlightLevelChanged;
-(void)audioDeviceControllerAudioRoutesChanged:(id)changed;
-(void)audioDeviceControllerMediaServerDied:(id)died;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(void)switcherPopoverController:(id)controller willRotateToOrientation:(int)orientation duration:(double)duration;
-(void)switcherPopoverController:(id)controller didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)viewControllerRequestsDismissal:(id)dismissal;
@end

