/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIcon.h"


@interface SBNullIcon : SBIcon {
}
+(id)nullIcon;
-(id)generateIconImage:(int)image;
-(BOOL)shouldCacheImageForFormat:(int)format;
@end

