/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet;

@interface SBOrientationLockManager : XXUnknownSuperclass {
	NSMutableSet* _lockOverrideReasons;
	int _userLockedOrientation;
}
+(id)sharedInstance;
-(void)restoreStateFromPrefs;
-(id)init;
-(void)dealloc;
-(void)lock;
-(void)lock:(int)lock;
-(void)unlock;
-(BOOL)isLocked;
-(int)userLockOrientation;
-(void)setLockOverrideEnabled:(BOOL)enabled forReason:(id)reason;
-(void)enableLockOverrideForReason:(id)reason suggestOrientation:(int)orientation;
-(void)enableLockOverrideForReason:(id)reason forceOrientation:(int)orientation;
-(BOOL)lockOverrideEnabled;
-(void)updateLockOverrideForCurrentDeviceOrientation;
-(void)_updateLockStateWithChanges:(id)changes;
-(void)_updateLockStateWithOrientation:(int)orientation changes:(id)changes;
-(void)_updateLockStateWithOrientation:(int)orientation forceUpdateHID:(BOOL)hid changes:(id)changes;
-(BOOL)_effectivelyLocked;
@end

