/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UILabel;

@interface SBPasscodeTextField : XXUnknownSuperclass {
	float _letterSpacing;
	BOOL _usesLargeClearButton;
	UILabel* _hiddenLabel;
}
@property(assign, nonatomic) float letterSpacing;
@property(assign, nonatomic) BOOL usesLargeClearButton;
-(void)dealloc;
-(CGRect)clearButtonRectForBounds:(CGRect)bounds;
-(id)createTextLabelWithTextColor:(id)textColor;
-(void)attachFieldEditor:(id)editor;
-(void)_endedEditing;
-(id)_style;
-(void)_handleKeyEvent:(GSEventRef)event;
-(BOOL)becomeFirstResponder;
-(BOOL)resignFirstResponder;
@end

