/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFluidSlideGestureRecognizer.h"


@interface SBPanGestureRecognizer : SBFluidSlideGestureRecognizer {
	float _arcCenter;
	float _arcSize;
	BOOL _recognizesHorizontalPanning;
	BOOL _recognizesVerticalPanning;
}
-(id)init;
-(id)initForHorizontalPanning;
-(id)initForVerticalPanning;
-(float)computeIncrementalGestureMotion:(SBGestureContextRef)motion;
-(void)updateForBeganOrMovedTouches:(SBGestureContextRef)beganOrMovedTouches;
@end

