/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBPasscodeField : XXUnknownSuperclass {
	int _style;
	float _okFontSize;
	float _cancelFontSize;
	float _buttonWidth;
	BOOL _showsCancelButton;
	BOOL _isAlphanumericField;
}
@property(assign, nonatomic) BOOL isAlphanumericField;
@property(assign, nonatomic) BOOL showsCancelButton;
@property(assign, nonatomic) int clearButtonMode;
@property(assign, nonatomic, getter=isOkayButtonEnabled) BOOL okayButtonEnabled;
+(Class)textFieldClass;
-(id)initWithStyle:(int)style;
-(id)_entryField;
-(void)setNumberOfEntryFields:(int)entryFields opaqueBackground:(BOOL)background;
-(void)setShowsOKButton:(BOOL)button;
-(id)textInputTraits;
-(id)_localizedOKString;
-(id)_localizedCancelString;
-(void)_updateButtonMetrics;
-(void)_updateButtonTitle;
-(void)_updateButtonFrame;
-(void)_updateFields;
-(BOOL)textFieldShouldClear:(id)textField;
-(void)_textDidChange;
@end

