/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface SBPhraseInterpretation : XXUnknownSuperclass {
	int _weight;
}
@property(assign, nonatomic) int weight;
@property(readonly, retain, nonatomic) NSString* text;
-(id)init;
-(BOOL)removeSpaceBefore;
-(BOOL)removeSpaceAfter;
-(id)description;
@end

