/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface SBPhoneAlertItem : XXUnknownSuperclass {
	NSString* _bodyText;
	NSString* _title;
}
-(id)initWithTitle:(id)title bodyText:(id)text;
-(void)dealloc;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
@end

