/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface SBPluginManager : XXUnknownSuperclass {
	NSString* _pluginsDirectory;
}
+(id)sharedInstance;
-(id)springBoardPluginsDirectory;
-(void)loadAllLaunchPlugins;
-(Class)loadPluginNamed:(id)named;
-(Class)loadPluginBundle:(id)bundle;
@end

