/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBPolygon : XXUnknownSuperclass {
	int m_pointCount;
	CGPoint m_points[5];
	unsigned m_pathIDs[5];
	float m_weights[5];
	CGPoint m_centroid;
	CGPoint m_weightedCentroid;
	unsigned m_baseLeftVertex;
	unsigned m_bottomRightVertex;
}
@property(readonly, assign, nonatomic) int pointCount;
@property(assign, nonatomic) CGPoint centroid;
@property(assign, nonatomic) CGPoint weightedCentroid;
@property(readonly, assign, nonatomic) BOOL isLeftHanded;
+(BOOL)candidate:(id)candidate matchesTemplate:(id)aTemplate transforms:(int)transforms acceptFactor:(float)factor;
-(void)commonInit;
-(void)makeLike:(id)like;
-(void)clear;
-(void)beginPointUpdate;
-(void)addPoint:(CGPoint)point;
-(void)addPoint:(CGPoint)point pathIndex:(unsigned)index;
-(void)endPointUpdate;
-(float)weightAtIndex:(int)index;
-(float)width;
-(float)height;
-(unsigned)thumbIndex;
-(void)rotate:(float)rotate;
-(void)scale:(float)scale;
-(void)flipHorizontally;
-(void)sortAlongOutsideEdge;
-(float)findLongestOutsideEdge;
-(CGPoint)calculateCentroid;
-(CGPoint)calculateWeightedCentroid;
-(float)baseOrientation;
-(float)meanFingertipRowAngle;
-(float)meanRadius;
@end

