/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

@interface SBProximitySensorInterface : XXUnknownSuperclass {
	int _lockedMode;
	int _currentMode;
	int _lastSetMode;
	NSMutableDictionary* _pidToClients;
	dispatch_queue_s* _clientQueue;
}
+(id)sharedInstance;
+(int)_HIDDetectionModeForSBDetectionMode:(int)sbdetectionMode;
-(id)init;
-(void)dealloc;
-(int)_queue_currentMode;
-(int)currentMode;
-(int)requestedMode;
-(void)_updateProximityDetectionMode;
-(BOOL)_addClient:(id)client;
-(BOOL)_removeClient:(id)client;
-(id)_existingClientForPID:(int)pid;
-(void)clientEstablished:(id)established;
-(void)clientDied:(id)died;
-(int)_detectionModeForSBSDetectionMode:(int)sbsdetectionMode;
-(BOOL)_updateClientPID:(int)pid clientPort:(unsigned)port withDetectionMode:(int)detectionMode;
-(BOOL)clientRequestedProximityMode:(int)mode processID:(int)anId clientPort:(unsigned)port;
-(void)requestProximityMode:(int)mode;
-(void)disableProximityDetection;
-(void)enableProximityDetectionWithMode:(int)mode;
@end

