/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBLeafIcon.h"


@interface SBPrintStatusIcon : SBLeafIcon {
}
-(id)generateIconImage:(int)image;
-(id)displayName;
-(id)leafIdentifier;
-(BOOL)shouldEllipsizeLabel;
-(id)applicationBundleID;
-(BOOL)delaysUnhighlightWhenTapped;
@end

