/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, CPDistributedNotificationCenter;

@interface SBProcessAssertionManager : XXUnknownSuperclass {
	NSMutableArray* _clients;
	CPDistributedNotificationCenter* _notificationCenter;
	opaque_pthread_mutex_t _clientMutex;
}
+(id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;
+(id)sharedInstance;
+(id)sharedInstanceIfExists;
-(id)init;
-(void)dealloc;
-(id)_assertionForPort:(unsigned)port;
-(BOOL)acquireAssertionForProcessID:(int)processID ownerProcessID:(int)anId withClientPort:(unsigned)clientPort flags:(unsigned)flags reason:(unsigned)reason identifier:(id)identifier;
-(void)_relinquishAssertion:(id)assertion;
-(void)setAssertionFlagsForPort:(unsigned)port flags:(unsigned)flags;
-(void)processExited:(id)exited;
@end

