/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol SBProximityDetectionClientDelegate;

@interface SBProximityDetectionClient : XXUnknownSuperclass {
	int _pid;
	unsigned _port;
	int _requestedMode;
	dispatch_source_s* _source;
	id<SBProximityDetectionClientDelegate> _delegate;
}
@property(assign, getter=PID, setter=setPID:) int pid;
@property(assign) int requestedMode;
@property(assign, nonatomic) unsigned port;
@property(assign, nonatomic) id delegate;
-(id)init;
-(id)initWithPID:(int)pid port:(unsigned)port delegate:(id)delegate;
-(void)dealloc;
-(id)description;
-(BOOL)isValid;
@end

