/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBApplication;

@interface SBRemoteNotificationPermissionAlert : XXUnknownSuperclass {
	SBApplication* _app;
	int _types;
}
-(id)initWithApplication:(id)application notificationTypes:(int)types;
-(void)dealloc;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(BOOL)shouldShowInLockScreen;
@end

