/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIColor, UIBezierPath;

@interface SBResetProgressView : XXUnknownSuperclass {
	UIColor* _progressColor;
	UIBezierPath* _path;
	float _resetProgress;
}
-(void)dealloc;
-(void)setResetProgress:(float)progress;
-(id)_outlinePath;
-(id)_progressColor;
-(void)drawRect:(CGRect)rect;
@end

