/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

@interface SBRemoteViewsController : XXUnknownSuperclass {
	NSMutableDictionary* _registeredRemoteViewInfos;
	NSMutableDictionary* _unregisteredRemoteViewInfos;
}
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)unregisterProxyRemoteView:(id)view;
-(void)registerRemoteContextID:(unsigned)anId forIdentifier:(id)identifier opaque:(BOOL)opaque size:(CGSize)size application:(id)application;
-(void)unregisterRemoteIdentifier:(id)identifier application:(id)application;
-(id)_createProxyRemoteViewForIdentifier:(id)identifier;
-(void)_sequesterProxyRemoteView:(id)view;
-(id)proxyRemoteViewForIdentifier:(id)identifier;
-(void)unregisterRemoteViewsForApplication:(id)application;
@end

