/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBApplication;

@interface SBRemoteNotificationNeedIdentityAlert : XXUnknownSuperclass {
	SBApplication* _app;
}
-(id)initWithApplication:(id)application;
-(void)dealloc;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(BOOL)dismissOnLock;
-(BOOL)dismissOnModalDisplayActivation;
@end

