/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBHUDView.h"


@interface SBRingerHUDView : SBHUDView {
	BOOL _silent;
}
@property(assign, nonatomic, getter=isSilent) BOOL silent;
-(void)_updateSilentImage;
-(id)init;
@end

