/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBRotationLockHUDController : XXUnknownSuperclass {
}
+(void)activateWithLocked:(BOOL)locked;
@end

