/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class SBWallpaperClipView, UIView;

@interface SBRoundedCornersView : XXUnknownSuperclass {
	float _cornerRadius;
	UIView* _contentView;
	SBWallpaperClipView* _topLeftCorner;
	SBWallpaperClipView* _topRightCorner;
	SBWallpaperClipView* _bottomLeftCorner;
	SBWallpaperClipView* _bottomRightCorner;
}
-(id)initWithFrame:(CGRect)frame cornerRadius:(float)radius content:(id)content wallpaperView:(id)view;
-(void)updateWallpaperOffsets;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
@end

