/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBRoundedMaskCornerView : XXUnknownSuperclass {
	float _cornerRadius;
	unsigned _corner;
}
-(id)initWithCorner:(unsigned)corner radius:(float)radius;
-(void)drawRect:(CGRect)rect;
@end

