/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBSDaemonRequest : XXUnknownSuperclass {
	id _enabler;
	id _disabler;
}
@property(copy, nonatomic) id enabler;
@property(copy, nonatomic) id disabler;
+(id)requestWithEnabler:(id)enabler disabler:(id)disabler;
-(void)dealloc;
-(void)dispatchEnablerOnQueue:(dispatch_queue_s*)queue;
-(void)dispatchDisablerOnQueue:(dispatch_queue_s*)queue;
@end

