/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBSDaemonHandler : XXUnknownSuperclass {
}
+(void)initialize;
+(BOOL)addRequest:(id)request forKey:(id)key forDaemonPid:(int)daemonPid;
+(void)removeRequestForKey:(id)key forDaemonPid:(int)daemonPid;
+(id)stateDescription;
+(void)noteDaemonCanceled:(id)canceled;
@end

