/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class SBNoResultsView, UISearchBar, UIView, SBRoundedCornersView, UITableView, UILabel;

@interface SBSearchView : XXUnknownSuperclass {
	SBRoundedCornersView* _roundedCornersView;
	UISearchBar* _searchBar;
	UITableView* _tableView;
	UILabel* _noResultsLabel;
	SBNoResultsView* _noResultsView;
	UIView* _rootView;
	UIView* _contentView;
	BOOL _isKeyboardAnimatingRotation;
	BOOL _hidesEmptyTableFooter;
	BOOL _translatedKbForScatter;
}
@property(readonly, assign, nonatomic) UISearchBar* searchBar;
@property(readonly, assign, nonatomic) UITableView* tableView;
@property(retain, nonatomic) UIView* contentView;
@property(retain, nonatomic) UIView* rootView;
@property(readonly, assign, nonatomic) UIView* roundedCornersView;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame withContent:(id)content onWallpaper:(id)wallpaper;
-(void)dealloc;
-(void)didMoveToWindow;
-(void)setFrame:(CGRect)frame;
-(void)scrollViewIsScrollingHorizontally;
-(void)setShowsNoResultsView:(BOOL)view;
-(void)layoutCornerView;
-(void)setHidesEmptyTableFooter:(BOOL)footer;
-(float)_footerHeight;
-(void)layoutFooterView;
-(void)_layoutNoResultsView;
-(Class)tableViewClass;
-(Class)searchBarClass;
-(id)_keyboard;
-(BOOL)isKeyboardMinimized;
-(BOOL)isKeyboardVisible;
-(void)setShowsKeyboard:(BOOL)keyboard animated:(BOOL)animated;
-(void)keyboardDidShow:(id)keyboard;
-(void)setShowingNoResultsText:(BOOL)text;
-(void)_setDistantContentViewTransform;
-(void)_resetContentViewTransform;
-(void)_resetKeyboardTransformForScatter;
-(void)cleanupKeyboardForScatterIfNecessary;
-(void)scatter:(BOOL)scatter startTime:(double)time;
-(void)unscatter:(BOOL)unscatter startTime:(double)time;
-(void)unscatterAnimationDidStop;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
@end

