/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIFont, NSString;

@interface SBSearchTableViewCell : XXUnknownSuperclass {
	UIFont* _titleFont;
	UIFont* _subtitleFont;
	UIFont* _topHitFont;
	NSString* _title;
	NSString* _subtitle;
	NSString* _summary;
	NSString* _auxiliaryTitle;
	NSString* _auxiliarySubtitle;
	BOOL _badged;
	BOOL _usesAlternateBackgroundColor;
	BOOL _isTopHit;
	BOOL _isBelowTopHit;
	BOOL _isFirstInTableView;
	BOOL _isFirstInSection;
	float _sectionHeaderWidth;
	float _edgeInset;
}
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) NSString* subtitle;
@property(retain, nonatomic) NSString* summary;
@property(retain, nonatomic) NSString* auxiliaryTitle;
@property(retain, nonatomic) NSString* auxiliarySubtitle;
@property(assign, nonatomic, getter=isBadged) BOOL badged;
@property(assign, nonatomic) BOOL usesAlternateBackgroundColor;
@property(assign, nonatomic, getter=isTopHit) BOOL topHit;
@property(assign, nonatomic, getter=isBelowTopHit) BOOL belowTopHit;
@property(assign, nonatomic, getter=isFirstInTableView) BOOL firstInTableView;
@property(assign, nonatomic, getter=isFirstInSection) BOOL firstInSection;
@property(assign, nonatomic) float sectionHeaderWidth;
@property(assign, nonatomic) float edgeInset;
+(void)initialize;
+(id)backgroundColor;
+(id)alternateBackgroundColor;
+(id)lineColor;
+(id)alternateLineColor;
+(id)topLineShadowColor;
+(id)outer2xShadowColor;
+(id)inner2xShadowColor;
+(id)outer2xLineColor;
+(id)inner2xLineColor;
+(id)outer2xAlternateShadowColor;
+(id)inner2xAlternateShadowColor;
+(id)outer2xAlternateLineColor;
+(id)inner2xAlternateLineColor;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(void)dealloc;
-(void)clearContents;
-(BOOL)_drawsContent;
-(void)_drawContentInRect:(CGRect)rect selected:(BOOL)selected;
-(void)drawRect:(CGRect)rect;
-(id)_scriptingInfo;
@end

