/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"


@interface SBSIMLockEntryAlert : SBAlert {
	int _status;
}
-(id)init;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(int)status;
-(void)activate;
-(void)deactivate;
@end

