/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBSIMLockAlertItem : XXUnknownSuperclass {
	int _status;
	int _okButtonIndex;
	int _unlockButtonIndex;
}
+(id)alertTitleForStatus:(int)status languageCode:(id)code;
+(id)alertTitleForStatus:(int)status;
-(id)initWithStatus:(int)status;
-(void)_resetButtonIndexes;
-(void)dealloc;
-(BOOL)canUnlock;
-(id)alertTitleForLanguageCode:(id)languageCode;
-(id)alertTextForLanguageCode:(id)languageCode;
-(int)status;
-(void)didDeactivateForReason:(int)reason;
-(void)unlock;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)performUnlockAction;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(id)lockLabel;
-(BOOL)forcesModalAlertAppearance;
-(BOOL)allowInSetup;
-(BOOL)pendInSetupIfNotAllowed;
-(BOOL)reappearsAfterUnlock;
-(BOOL)reappearsAfterLock;
@end

