/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIImageView;

@interface SBSlidingViewHighlight : XXUnknownSuperclass {
	UIImageView* _leftHighlight;
	UIImageView* _rightHighlight;
	CGRect _notchRect;
}
+(float)defaultHeight;
+(id)highlightImage;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame notchRect:(CGRect)rect;
-(void)layoutSubviews;
-(void)setNotchRect:(CGRect)rect;
-(void)dealloc;
@end

