/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUSSDAlert.h"


@interface SBSMSClass0Alert : SBUSSDAlert {
}
+(void)registerForAlerts;
+(BOOL)shouldPlayMessageReceived;
+(void)playMessageReceived;
+(void)defaultAlertTonePrefChanged;
-(void)_unregisterForNotifications;
-(void)_registerForNotifications;
-(id)initWithString:(id)string;
-(void)deactivate;
@end

