/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBSoundPreferences.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBSoundPreferences : XXUnknownSuperclass {
}
+(void)userDefaultsDidChanged:(id)userDefaults;
+(id)calendarAlarmPath;
+(id)ringtoneIdentifier;
+(id)ringtonePath;
+(BOOL)playLockSound;
+(id)vibratePattern;
+(BOOL)vibrateWhenRinging;
+(BOOL)vibrateWhenSilent;
+(BOOL)shouldVibrateForCurrentRingerState;
@end

@interface SBSoundPreferences (Private)
+(void)_loadDefaultsIfNeeded;
@end

