/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBaseSoftwareUpdateAlertItem.h"


@interface SBSoftwareUpdateAvailableAlertItem : SBBaseSoftwareUpdateAlertItem {
}
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(BOOL)reappearsAfterUnlock;
-(BOOL)dismissOnLock;
@end

