/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBaseSoftwareUpdateAlertItem.h"

@class NSTimer;

@interface SBSoftwareUpdateForcedInstallAlertItem : SBBaseSoftwareUpdateAlertItem {
	NSTimer* _timer;
	unsigned _timeLeftUntilInstall;
	BOOL _delayOnDismissForNonUserAction;
	BOOL _delayAfterNextUnlock;
}
@property(assign, nonatomic) BOOL delayOnDismissForNonUserAction;
@property(assign, nonatomic) BOOL delayAfterNextUnlock;
-(id)initWithDescriptor:(id)descriptor;
-(void)dealloc;
-(void)_installUpdate;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)updateBodyText;
-(void)willPresentAlertView:(id)view;
-(void)willDeactivateForReason:(int)reason;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)_timerFired;
-(BOOL)undimsScreen;
-(BOOL)allowMenuButtonDismissal;
-(id)lockLabel;
-(id)shortLockLabel;
-(BOOL)shouldShowInLockScreen;
-(void)performUnlockAction;
-(BOOL)dismissOnLock;
@end

