/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBPhraseInterpretation.h"

@class NSArray;

@interface SBSpeechTokenInterpretation : SBPhraseInterpretation {
	NSArray* _speechTokens;
}
-(id)initWithSpeechTokens:(id)speechTokens;
-(BOOL)removeSpaceBefore;
-(BOOL)removeSpaceAfter;
-(void)dealloc;
-(id)text;
@end

