/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, SBStretchTransformer, SBApplication;

@interface SBSwitchAppGestureView : XXUnknownSuperclass {
	int m_orientation;
	SBApplication* m_startingApp;
	SBApplication* m_endingApp;
	SBApplication* m_leftwardApp;
	SBApplication* m_rightwardApp;
	int m_startingViewOrientation;
	int m_leftwardViewOrientation;
	int m_rightwardViewOrientation;
	UIView* m_startingView;
	UIView* m_leftwardView;
	UIView* m_rightwardView;
	float m_pageWidth;
	float m_percentage;
	float m_contentOffset;
	SBStretchTransformer* m_stretchTransformer;
	BOOL m_finishingPaging;
	BOOL m_underflowing;
	BOOL m_overflowing;
	id m_completion;
}
@property(assign, nonatomic) int orientation;
@property(retain, nonatomic) SBApplication* startingApp;
@property(retain, nonatomic) SBApplication* endingApp;
@property(retain, nonatomic) SBApplication* leftwardApp;
@property(retain, nonatomic) SBApplication* rightwardApp;
@property(retain, nonatomic) UIView* startingView;
@property(retain, nonatomic) UIView* leftwardView;
@property(retain, nonatomic) UIView* rightwardView;
@property(assign, nonatomic) int startingViewOrientation;
@property(assign, nonatomic) int leftwardViewOrientation;
@property(assign, nonatomic) int rightwardViewOrientation;
@property(assign, nonatomic) float pageWidth;
@property(assign, nonatomic) float percentage;
@property(assign, nonatomic) float contentOffset;
@property(retain, nonatomic) SBStretchTransformer* stretchTransformer;
@property(assign, nonatomic) BOOL underflowing;
@property(assign, nonatomic) BOOL overflowing;
@property(copy, nonatomic) id completion;
@property(readonly, assign, nonatomic) BOOL pagingRightward;
@property(readonly, assign, nonatomic) BOOL pagingLeftward;
-(id)initWithInterfaceOrientation:(int)interfaceOrientation startingApp:(id)app leftwardApp:(id)app3 rightwardApp:(id)app4;
-(void)dealloc;
-(void)transformGestureViewContainer:(id)container;
-(id)viewForApp:(id)app;
-(void)beginPaging;
-(void)updatePaging:(float)paging;
-(void)finishForwardToEndWithPercentage:(float)percentage completion:(id)completion;
-(void)finishBackwardToStartWithCompletion:(id)completion;
-(float)contentOffsetForApp:(id)app;
-(float)percentageForApp:(id)app;
-(float)scaleForPercentage:(float)percentage;
-(float)opacityForPercentage:(float)percentage;
-(void)moveToApp:(id)app;
-(void)moveToApp:(id)app animated:(BOOL)animated;
-(void)moveToContentOffset:(float)contentOffset percentage:(float)percentage animated:(BOOL)animated;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)stretchTransformerAnimationDidStop:(BOOL)stretchTransformerAnimation;
-(BOOL)isPagingUnderflowPercentage:(float)percentage;
-(BOOL)isPagingOverflowPercentage:(float)percentage;
@end

