/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"


@interface SBSwitcherVolumeSlider : XXUnknownSuperclass {
}
-(id)initWithFrame:(CGRect)frame;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(CGRect)trackRectForBounds:(CGRect)bounds;
-(CGRect)thumbRectForBounds:(CGRect)bounds trackRect:(CGRect)rect value:(float)value;
-(UIEdgeInsets)_thumbHitEdgeInsets;
-(void)setSliderEnabled:(BOOL)enabled withDuration:(double)duration;
@end

