/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBSwitcherPopoverWindowControllerDelegate <NSObject>
@optional
-(void)switcherPopoverController:(id)controller willRotateToOrientation:(int)orientation duration:(double)duration;
-(void)switcherPopoverController:(id)controller didRotateFromInterfaceOrientation:(int)interfaceOrientation;
@end

