/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSTimer, SBApplication;
@protocol SBSystemLocalNotificationAlertDelegate;

@interface SBSystemLocalNotificationAlert : XXUnknownSuperclass {
	id<SBSystemLocalNotificationAlertDelegate> _delegate;
	SBApplication* _app;
	NSString* _body;
	NSString* _actionLabel;
	NSString* _customLockLabel;
	NSString* _alertLaunchImage;
	BOOL _showActionButton;
	BOOL _hideTitle;
	BOOL _allowSnooze;
	NSTimer* _ringtoneAutoMuteTimer;
	unsigned _launchButtonIndex;
	unsigned _snoozeButtonIndex;
	id _context;
}
@property(assign, nonatomic) id<SBSystemLocalNotificationAlertDelegate> delegate;
@property(assign, nonatomic) BOOL hideTitle;
@property(assign, nonatomic) BOOL allowSnooze;
@property(retain, nonatomic) NSString* customLockLabel;
@property(retain, nonatomic) NSString* alertLaunchImage;
@property(retain, nonatomic) id context;
@property(readonly, assign, nonatomic) SBApplication* application;
+(id)presentWithLocalNotification:(id)localNotification application:(id)application;
+(id)localizedStringFromKey:(id)key defaultValue:(id)value inBundle:(id)bundle arguments:(id)arguments;
+(id)alertMatchingContext:(id)context;
+(void)playAlertSound:(BOOL)sound soundName:(id)name inBundle:(id)bundle isRingtone:(BOOL)ringtone sandboxPath:(id)path;
+(BOOL)isPlayingRingtone;
+(void)stopPlayingAlertSoundOrRingtone;
-(id)initWithApplication:(id)application body:(id)body showActionButton:(BOOL)button actionLabel:(id)label;
-(void)dealloc;
-(Class)alertSheetClass;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(id)lockLabel;
-(float)lockLabelFontSize;
-(BOOL)shouldShowInEmergencyCall;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)performUnlockAction;
-(void)willDeactivateForReason:(int)reason;
-(void)snoozeIfPossible;
-(void)snoozeOrDismiss;
-(void)dismiss:(int)dismiss;
-(void)startRingtoneAutoMuteTimer;
-(void)_ringtoneAutoMuteTimerFired;
-(void)stopRingtoneAutoMuteTimer;
-(int)alertItemNotificationType;
-(id)alertItemNotificationSender;
-(int)alertPriority;
@end

