/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBSystemLocalNotificationAlertSheet : XXUnknownSuperclass {
	BOOL _lockToPortrait;
}
-(void)setLockToPortrait:(BOOL)portrait;
-(BOOL)requiresPortraitOrientation;
@end

