/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

@interface SBTransientSettings : XXUnknownSuperclass {
	NSMutableDictionary* _transientSettings;
	BOOL _dirty;
}
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)setValue:(id)value forKey:(id)key;
-(id)objectForKey:(id)key;
-(void)reload;
-(void)save;
-(id)_path;
-(void)_load;
@end

