/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBTVOutController : XXUnknownSuperclass {
	int _tvOutMode;
}
@property(assign, nonatomic) int tvOutMode;
@property(readonly, assign, nonatomic) BOOL isTVSignalTypeDigital;
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)addClone:(id)clone;
-(void)setInitialTVModeIfNeeded;
-(void)updateLayerKitSettings;
-(void)updateSettings;
-(void)_handleIapServerConnectionDied;
-(void)_tetherSettingChanged:(id)changed;
-(void)_updateAVRoutes;
-(void)_pickableRoutesChanged:(id)changed;
-(void)_mediaServerConnectionDied:(id)died;
-(void)startListeningForSettingsChanges;
-(void)startListeningForAVSystemControllerNotifications;
-(void)stopListeningForAVSystemControllerNotifications;
-(void)stopListeningForSettingsChanges;
@end

