/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"

@class SBAlertDisplay, SBUIFullscreenAlertController;

@interface SBUIFullscreenAlertAdapter : SBAlert {
	SBUIFullscreenAlertController* _alertController;
	SBAlertDisplay* _alertDisplay;
}
-(id)initWithAlertController:(id)alertController;
-(BOOL)allowsEventOnlySuspension;
-(BOOL)hasTranslucentBackground;
-(void)dealloc;
-(void)deactivate;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(BOOL)viewIsReadyToBeRemoved;
-(BOOL)viewDisplaysAboveStatusBar;
-(void)setViewShouldAnimateIn:(BOOL)animateIn;
-(void)prepareViewToAnimateOut;
-(void)animateViewOut;
-(void)_pluginViewAnimatedOut:(id)anOut;
-(id)alertController;
-(void)alertWindowResizedFromContentFrame:(CGRect)contentFrame toContentFrame:(CGRect)contentFrame2;
-(void)alertWindowWillRotateToInterfaceOrientation:(int)alertWindow duration:(double)duration;
-(void)alertWindowWillAnimateRotationToInterfaceOrientation:(int)alertWindow duration:(double)duration;
-(void)alertWindowDidRotateFromInterfaceOrientation:(int)alertWindow;
-(BOOL)handleMenuButtonTap;
-(BOOL)handleLockButtonPressed;
-(BOOL)handleVolumeUpButtonPressed;
-(BOOL)handleVolumeDownButtonPressed;
-(BOOL)handleHeadsetButtonPressed:(BOOL)pressed;
-(void)launchSucceeded:(BOOL)succeeded;
-(id)description;
@end

