/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlertDisplay.h"

@class UIView;

@interface SBUIFullscreenAlertViewAdapter : SBAlertDisplay {
	UIView* _alertView;
}
-(id)_alertAdapter;
-(id)initWithFrame:(CGRect)frame andContentView:(id)view;
-(void)dealloc;
-(BOOL)isReadyToBeRemovedFromView;
-(BOOL)displaysAboveStatusBar;
-(void)alertDisplayWillBecomeVisible;
-(BOOL)shouldAnimateIconsIn;
-(void)viewAnimatedOut;
-(void)dismiss;
-(void)setShouldAnimateIn:(BOOL)animateIn;
-(void)alertWindowResizedFromContentFrame:(CGRect)contentFrame toContentFrame:(CGRect)contentFrame2;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
@end

