/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBApplicationIcon.h"


@interface SBUserInstalledApplicationIcon : SBApplicationIcon {
}
-(BOOL)allowsUninstall;
-(void)completeUninstall;
-(BOOL)hasBeenSyncedBackToITunes;
-(id)ratingsAlertTitle;
-(id)ratingsAlertBody;
-(id)ratingsAlertSkipTitle;
-(id)ratingsAlertRateButtonTitle;
-(id)uninstallAlertTitle;
-(id)uninstallAlertTitleForAppWithDocumentsInCloud;
-(id)uninstallAlertTitleForAppWithDocumentUpdatesPending;
-(id)uninstallAlertBody;
-(id)uninstallAlertBodyForAppWithDocumentsInCloud;
-(id)uninstallAlertBodyForAppWithDocumentUpdatesPending;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertCancelTitle;
@end

