/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBUserNotificationCenter : XXUnknownSuperclass {
}
+(void)startUserNotificationCenter;
+(void)_userNotificationDone:(id)done;
@end

