/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSTimer, AVController, UIImage, NSDictionary;

@interface SBUserNotificationAlert : XXUnknownSuperclass {
	unsigned _replyPort;
	int _token;
	int _timeout;
	unsigned _requestFlags;
	NSString* _alertHeader;
	id _alertMessage;
	NSString* _alertMessageDelimiter;
	NSString* _defaultButtonTitle;
	NSString* _alternateButtonTitle;
	NSString* _otherButtonTitle;
	NSString* _soundPath;
	NSDictionary* _avControllerAttributes;
	NSDictionary* _avItemAttributes;
	double _soundRepeatDuration;
	NSTimer* _soundStopTimer;
	id _keyboardTypes;
	id _autocapitalizationTypes;
	id _autocorrectionTypes;
	id _textFieldButtonDisplayDefaultButtonURLs;
	id _textFieldButtonImagePaths;
	id _textFieldTitles;
	id _textFieldValues;
	id _textFieldButtonDisplayTitles;
	id _textFieldButtonDisplayDefaultButtonTitles;
	int _currentTextFieldButtonDisplayIndex;
	double _creationTime;
	int _defaultButtonTag;
	int _unlockActionButtonTag;
	unsigned _replyFlags;
	int _defaultButtonIndex;
	int _alternateButtonIndex;
	int _otherButtonIndex;
	unsigned _cancel : 1;
	unsigned _isActivated : 1;
	unsigned _aboveLock : 1;
	unsigned _hideButtonsInAwayView : 1;
	unsigned _dismissOnLock : 1;
	unsigned _dontDismissOnUnlock : 1;
	unsigned _allowMenuButtonDismissal : 1;
	unsigned _oneButtonPerLine : 1;
	unsigned _groupsTextFields : 1;
	unsigned _configuredLocked : 1;
	unsigned _configuredNeedsPasscode : 1;
	UIImage* _alertImage;
	AVController* _avController;
}
@property(retain) id keyboardTypes;
@property(retain) id autocapitalizationTypes;
@property(retain) id autocorrectionTypes;
@property(retain) id textFieldButtonImagePaths;
@property(retain) id textFieldButtonDisplayDefaultButtonURLs;
@property(retain) id textFieldTitles;
@property(retain) id textFieldValues;
@property(retain) id textFieldButtonDisplayTitles;
@property(retain) id textFieldButtonDisplayDefaultButtonTitles;
@property(retain) NSString* soundPath;
@property(retain) NSDictionary* avControllerAttributes;
@property(retain) NSDictionary* avItemAttributes;
@property(retain) NSString* alertHeader;
@property(retain) NSString* alertMessage;
@property(retain) NSString* alertMessageDelimiter;
@property(retain) NSString* defaultButtonTitle;
@property(retain) NSString* alternateButtonTitle;
@property(retain) NSString* otherButtonTitle;
@property(retain) UIImage* alertImage;
-(id)_safeLocalizedValue:(id)value withBundle:(id)bundle;
-(id)initWithMessage:(id)message replyPort:(unsigned)port requestFlags:(int)flags;
-(void)updateWithMessage:(id)message requestFlags:(int)flags;
-(void)dealloc;
-(Class)alertSheetClass;
-(int)token;
-(BOOL)shouldShowInLockScreen;
-(BOOL)dismissOnLock;
-(BOOL)allowMenuButtonDismissal;
-(void)willActivate;
-(void)stopSound;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)wakeup;
-(void)cancel;
-(void)_setSheetDefaultButtonTitle:(id)title;
-(void)_textFieldButtonPressed:(id)pressed;
-(void)_sendResponse:(int)response;
-(BOOL)_needsDismissalWithClickedButtonIndex:(int)clickedButtonIndex;
-(void)performUnlockAction;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)noteVolumeOrLockPressed;
-(void)willDeactivateForReason:(int)reason;
-(void)didDeactivateForReason:(int)reason;
-(void)didFailToActivate;
@end

