/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

@interface SBUtterancePhrase : XXUnknownSuperclass {
	NSMutableArray* _interpretations;
}
-(id)init;
-(id)initWithInterpretations:(id)interpretations;
-(id)initWithString:(id)string;
-(void)dealloc;
-(id)description;
-(id)bestInterpretation;
-(id)interpretations;
@end

