/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBVODController : XXUnknownSuperclass {
}
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)_launchIPodIfNecessary;
@end

