/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBVoiceDisabledBundles : XXUnknownSuperclass {
}
+(void)setAppDisabledVoiceControl:(BOOL)control bundleIdentifier:(id)identifier;
+(BOOL)voiceControlDisabledByCurrentlyRunningApp;
@end

