/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIImageView;

@interface SBWallpaperView : XXUnknownSuperclass {
	int _orientation;
	int _variant;
	UIImageView* _topGradient;
	UIImageView* _bottomGradient;
	BOOL _usesFilter;
	float _gradientAlpha;
	CGRect _wallpaperContentsRect;
	BOOL _postsNotifications;
	BOOL _flushWallpaperAutomatically;
}
@property(assign, nonatomic) int orientation;
@property(readonly, assign, nonatomic) int variant;
@property(assign, nonatomic) float gradientAlpha;
@property(assign, nonatomic) BOOL postsNotifications;
@property(assign, nonatomic) BOOL flushWallpaperAutomatically;
@property(assign, nonatomic) BOOL usesFilter;
@property(assign, nonatomic) float filterAlpha;
-(id)initWithOrientation:(int)orientation variant:(int)variant;
-(void)dealloc;
-(void)setImage:(id)image;
-(void)_resetImage;
-(void)_wallpaperChanged;
-(void)_setGradientImagesWithOrientation:(int)orientation;
-(void)_setOrientation:(int)orientation duration:(double)duration force:(BOOL)force;
-(void)setOrientation:(int)orientation duration:(double)duration;
-(void)setViewAlpha:(float)alpha;
-(float)alpha;
-(void)setAlpha:(float)alpha;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(id)gradientImageForInterfaceOrientation:(int)interfaceOrientation;
-(CGRect)wallpaperContentsRect;
-(void)replaceWallpaperWithImage:(id)image;
-(void)resetCurrentImageToWallpaper;
-(void)didMoveToWindow;
@end

