/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBWallpaperClipView;

@interface SBWallpaperNotchView : XXUnknownSuperclass {
	XXStruct_9ihRqB _notchInfo;
	SBWallpaperClipView* _clipView;
}
-(id)initWithFrame:(CGRect)frame wallpaperView:(id)view notchInfo:(XXStruct_9ihRqB)info;
-(void)dealloc;
-(void)setNotchInfo:(XXStruct_9ihRqB)info;
-(void)drawRect:(CGRect)rect;
@end

