/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBulletinLinenBackedCell.h"

@class UIView, SBWeeApp;

@interface SBWeeAppCell : SBBulletinLinenBackedCell {
	SBWeeApp* _weeApp;
	UIView* _weeAppView;
	BOOL _useTopPadding;
}
@property(retain, nonatomic) SBWeeApp* weeApp;
+(float)rowHeightForViewHeight:(float)viewHeight withTopPadding:(BOOL)topPadding;
-(id)initWithLinenView:(id)linenView reuseIdentifier:(id)identifier;
-(void)dealloc;
-(void)setUsesTopPadding:(BOOL)padding;
-(void)layoutSubviews;
-(void)willMoveToWindow:(id)window;
-(void)didMoveToWindow;
-(void)prepareForReuse;
-(void)_tapped:(id)tapped;
@end

