/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBManualKeyboardTextField.h"


@interface WhiteBorderedTextField : SBManualKeyboardTextField {
}
-(void)drawBorder:(CGRect)border;
-(CGRect)textRect;
-(void)drawRect:(CGRect)rect;
@end

