/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (SBApplicationAdditions)
-(void)addObjectsFromDictionary:(id)dictionary forKeys:(id)keys;
@end

@interface XXUnknownSuperclass (SBArrayStackAdditions)
-(void)push:(id)push;
-(id)pop;
-(id)popObject:(id)object;
-(id)top;
@end

@interface XXUnknownSuperclass (Centerable)
-(void)centerToContentView;
@end

@interface XXUnknownSuperclass (PrefsNotifications)
-(void)addPrefNotification:(id)notification withUserInfo:(id)userInfo;
-(id)_callForwardingString:(id)string;
-(id)_callWaitingString:(id)string;
-(id)_callBarringString:(id)string;
-(id)_fixedDialingString:(id)string;
-(id)_connectedLinePresentationString:(id)string;
-(id)_callingLinePresentationString:(id)string;
-(id)_connectedLineIDRestrictionString:(id)string;
-(id)_callingLineIDRestrictionString:(id)string;
-(id)_simLockString:(id)string;
-(id)_serviceCenterAddressString:(id)string;
-(id)_ssPasswordString:(id)string;
-(id)_callingNamePresentationString:(id)string;
-(id)_alertStringForPref:(id)pref;
-(id)prefsNotificationsAlertString;
@end

@interface XXUnknownSuperclass (CTHelpers)
-(id)callClass;
-(id)callForwardingReason;
-(id)callBarringFacility;
-(id)callingLineIDRestrictionValue;
-(id)callingLinePresentationValue;
-(id)connectedLineIDRestrictionValue;
-(id)connectedLinePresentationValue;
-(id)enabledString;
-(id)serviceCenterAddress;
-(id)ssServiceType;
-(id)mmiProcedure;
-(CFStringRef)settingType;
-(id)callingNamePresentationValue;
@end

@interface XXUnknownSuperclass (AlertItemsAdditions)
-(id)objectOfClass:(Class)aClass;
-(void)addObjectsOfClass:(Class)aClass toArray:(id)array;
@end

@interface XXUnknownSuperclass (Formatting)
-(id)ICCID;
-(id)IMEI;
@end

@interface XXUnknownSuperclass (SBIconListNumberOffset)
-(void)setCurrentPageWithIconListNumber:(int)iconListNumber;
-(void)setNumberOfPagesWithIconListCount:(int)iconListCount;
@end

@interface XXUnknownSuperclass (SpringBoardMetadata)
-(id)cachedSoftwareType;
-(id)cachedBundleIdentifier;
-(id)cachedApplicationIdentifier;
-(BOOL)cachedArtworkIsPrerendered;
-(id)cachedTitle;
@end

@interface XXUnknownSuperclass (SBOptimizedCombination)
-(id)dictionaryByAddingEntriesFromDictionary:(id)dictionary;
@end

@interface XXUnknownSuperclass (SBDeviceLockEntryFieldExtras)
-(BOOL)isSingleCharacterAndMemberOfSet:(CFCharacterSetRef)set;
-(BOOL)isNewline;
@end

@interface XXUnknownSuperclass (LastIndex)
-(unsigned)lastIndex;
@end

@interface XXUnknownSuperclass (SBTypeSafety)
-(id)objectForKey:(id)key ofClass:(Class)aClass;
@end

@interface XXUnknownSuperclass (SBAssistantUtilities)
-(BOOL)isAssistantTelephonyURL;
@end

